# Tier A conformance (docs/AUDIT_REGISTER.md section 6): primitives vs the pinned upstream
# JAX FabricPC checkout, rtol 1e-6. Fixtures generated by
# scripts/generate_tier_a_fixtures.py into fixtures/tier_a.npz (see that script's docstring
# for the RNG-trap note and the grad_mu-via-autodiff rationale).
using Test
using NPZ
using FabricPC
import FabricPC: _tb_layernorm, _tb_rope_tables, _tb_apply_rope

const FIX = npzread(joinpath(@__DIR__, "fixtures", "tier_a.npz"))
const RTOL = 1.0f-6
const ATOL = 1.0f-6

# numpy.allclose semantics (per-element: |a-b| <= atol + rtol*|b|), NOT Julia's built-in
# array `≈` (a single norm-based check) — "rtol 1e-6" in the register means per-element.
allclose(a, b; rtol=RTOL, atol=ATOL) = all(abs.(a .- b) .<= atol .+ rtol .* abs.(b))

@testset "Tier A conformance (upstream JAX FabricPC, rtol 1e-6)" begin
    @testset "Activations: forward + derivative" begin
        # LeakyReLU/HardTanh use their default config (alpha=0.01 / min=-1,max=1), matching
        # the fixture generator's use of each class's own Python default.
        cases = [
            ("identity", IdentityActivation()),
            ("sigmoid", SigmoidActivation()),
            ("tanh", TanhActivation()),
            ("relu", ReLUActivation()),
            ("leaky_relu", LeakyReLUActivation()),
            ("gelu", GeluActivation()),
            ("softmax", SoftmaxActivation()),
            ("hard_tanh", HardTanhActivation())
        ]
        for (name, act) in cases
            x = FIX["act_$(name)_x"]
            fwd = forward(act, x)
            deriv = derivative(act, x) .* ones(Float32, size(x))  # broadcast Identity's scalar 1
            @test allclose(fwd, FIX["act_$(name)_fwd"])
            @test allclose(deriv, FIX["act_$(name)_deriv"])
        end
    end

    @testset "Softmax: full jacobian + outlier numerical stability" begin
        sm = SoftmaxActivation()
        x = FIX["act_softmax_x"]
        @test allclose(jacobian(sm, x), FIX["act_softmax_jac"])
        xo = FIX["act_softmax_outlier_x"]
        fwdo = forward(sm, xo)
        @test allclose(fwdo, FIX["act_softmax_outlier_fwd"])
        @test all(isfinite, fwdo)
    end

    @testset "Energies: energy + grad_latent + grad_mu" begin
        # grad_mu here checks Julia's hand-derived closed form against upstream's jax.grad
        # ground truth (upstream itself has no closed-form grad_mu — see the generator script).
        cases = [
            ("gaussian", GaussianEnergy()),
            ("bernoulli", BernoulliEnergy()),
            ("crossentropy", CrossEntropyEnergy()),
            ("laplacian", LaplacianEnergy()),
            ("huber", HuberEnergy()),
            ("kldivergence", KLDivergenceEnergy())
        ]
        for (name, en) in cases
            z = FIX["energy_$(name)_z"]
            mu = FIX["energy_$(name)_mu"]
            @test allclose(energy(en, z, mu), FIX["energy_$(name)_E"])
            @test allclose(grad_latent(en, z, mu), FIX["energy_$(name)_gradz"])
            @test allclose(grad_mu(en, z, mu), FIX["energy_$(name)_gradmu"])
        end
    end

    @testset "RoPE: cos/sin tables + rotation output + single-pair discriminator" begin
        S, half = size(FIX["rope_cos"])
        Dh = half * 2
        cosA, sinA = _tb_rope_tables(Dh, S)
        @test allclose(cosA, FIX["rope_cos"])
        @test allclose(sinA, FIX["rope_sin"])

        x = FIX["rope_random_x"]
        out = _tb_apply_rope(x, cosA, sinA)
        @test allclose(out, FIX["rope_random_out"])

        # single-nonzero-pair discriminator: pins down BOTH position indexing and the
        # adjacent-pair grouping convention — a random tensor could pass by coincidence
        # under a wrong pairing, this can't.
        xp = FIX["rope_single_pair_x"]
        Sp, Dhp = size(xp, 2), size(xp, 3)
        cosAp, sinAp = _tb_rope_tables(Dhp, Sp)
        outp = _tb_apply_rope(xp, cosAp, sinAp)
        @test allclose(outp, FIX["rope_single_pair_out"])
    end

    @testset "LayerNorm: standard + outlier numerical stability" begin
        x = FIX["ln_x"]
        gamma = FIX["ln_gamma"]
        beta = FIX["ln_beta"]
        E = length(gamma)
        g3 = reshape(gamma, 1, 1, E)
        b3 = reshape(beta, 1, 1, E)
        out = _tb_layernorm(x, g3, b3)
        @test allclose(out, FIX["ln_out"])

        xo = FIX["ln_outlier_x"]
        outo = _tb_layernorm(xo, g3, b3)
        @test allclose(outo, FIX["ln_outlier_out"])
        @test all(isfinite, outo)
    end
end
