# Tier C conformance (docs/AUDIT_REGISTER.md section 6): LOOP-level -- inference_step ->
# run_inference -> one train_step, on a real *assembled graph* x(4)->h(6,tanh)->y(3) (not an
# isolated node like Tier B) -- vs the pinned upstream JAX FabricPC checkout, rtol/atol 1e-5
# (Tier B's tolerance, appropriate for a multi-step loop rather than Tier A's tighter 1e-6
# primitive-level check). Fixtures generated by scripts/generate_tier_c_fixtures.py into
# fixtures/tier_c.npz (see that script's docstring for the RNG-trap note, the
# Linear-vs-LinearExplicitGrad node-class rationale, and the STATE-INIT RNG NON-ISSUE argument
# for why the rng_key argument never affects a single compared output array in this fixture).
using Test
using NPZ
using FabricPC
using Random

const FIX_C = npzread(joinpath(@__DIR__, "fixtures", "tier_c.npz"))

# numpy.allclose semantics (per-element: |a-b| <= atol + rtol*|b|), NOT Julia's built-in
# array `≈` (a single norm-based check) -- separate name from Tier A's `allclose`/Tier B's
# `allclose_b` (already `include`d earlier in runtests.jl and sharing this file's Main scope)
# so no tier's helper/constants shadow another's.
allclose_c(a, b; rtol=1.0f-5, atol=1.0f-5) = all(abs.(a .- b) .<= atol .+ rtol .* abs.(b))

const TIER_C_NODES = ("x", "h", "y")

"""
    check_tier_c_state(prefix, state)

Assert every dumped `GraphState` field (z_latent/z_mu/error/energy/
latent_grad, per node) for fixture prefix `prefix` (e.g. "init"/"step1"/"converged"/
"grad_final"/"trained_final") against the live Julia `state`.
"""
function check_tier_c_state(prefix::AbstractString, state::GraphState)
    for name in TIER_C_NODES
        ns = state.nodes[name]
        @test allclose_c(ns.z_latent, FIX_C["$(prefix)_$(name)_z_latent"])
        @test allclose_c(ns.z_mu, FIX_C["$(prefix)_$(name)_z_mu"])
        @test allclose_c(ns.error, FIX_C["$(prefix)_$(name)_error"])
        @test allclose_c(ns.energy, FIX_C["$(prefix)_$(name)_energy"])
        @test allclose_c(ns.latent_grad, FIX_C["$(prefix)_$(name)_latent_grad"])
        # SHAPE, not just values: energy is per-sample `(batch,)` on BOTH stacks, and upstream
        # b6f64ad moved only WHERE the batch->scalar sum happens (out of forward(), into the AD
        # call sites) — it never made state.energy a scalar. An `allclose` alone would let a
        # scalar-collapsed energy broadcast against the fixture and could pass whenever the
        # per-sample values happen to coincide; this fails on the shape first, which is the half
        # "matches upstream" hides. Same guard, same reason, in the D tiers.
        @test size(ns.energy) == size(FIX_C["$(prefix)_$(name)_energy"]) ==
            (state.batch_size,)
    end
end

"""
    check_tier_c_params(prefix, gp, edge_xh, edge_hy)

Assert the dumped `h`/`y` weights + biases for fixture prefix `prefix` (e.g. "grad"/
"trained") against the live Julia `GraphParams` `gp`. "x" carries no learnable params
(source node, `use_bias=false`) so there is nothing to compare for it.
"""
function check_tier_c_params(
    prefix::AbstractString, gp::GraphParams, edge_xh::AbstractString,
    edge_hy::AbstractString
)
    @test allclose_c(gp.nodes["h"].weights[edge_xh], FIX_C["$(prefix)_h_w__$(edge_xh)"])
    @test allclose_c(gp.nodes["h"].biases["b"], FIX_C["$(prefix)_h_b__b"])
    @test allclose_c(gp.nodes["y"].weights[edge_hy], FIX_C["$(prefix)_y_w__$(edge_hy)"])
    @test allclose_c(gp.nodes["y"].biases["b"], FIX_C["$(prefix)_y_b__b"])
end

@testset "Tier C conformance (upstream JAX FabricPC, loop-level, rtol/atol 1e-5)" begin
    B, DX, DH, DY = 3, 4, 6, 3

    # NODE-CLASS CHOICE mirrors generate_tier_c_fixtures.py's rationale exactly: Julia's
    # `Linear` is the FUSED explicit-grad node (linear.jl: "v0 is autodiff-free ... our node
    # IS the explicit path") -- it is used for ALL THREE nodes here, matching both the Python
    # side's "x"=Linear (terminal-source special case, use_bias=False) AND "h"/"y"=
    # LinearExplicitGrad (same closed-form math Tier B already validated bit-for-bit against
    # Julia's Linear at the isolated-node level -- this fixture is the loop-level extension).
    x = Linear((DX,), "x"; use_bias=false)
    h = Linear((DH,), "h"; activation=TanhActivation())
    y = Linear((DY,), "y"; energy=GaussianEnergy())

    inference = InferenceSGD(eta_infer=0.1, infer_steps=8, latent_decay=0.0)
    structure = graph(
        [x, h, y],
        [Edge(x, h), Edge(h, y)],
        TaskMap(x=x, y=y),
        inference
    )

    edge_xh = "x->h:in"
    edge_hy = "h->y:in"

    # RNG TRAP (same as Tier A/B, per the generator's docstring): GraphParams built DIRECTLY
    # from the fixture's JAX-generated arrays -- never via Julia's own `initialize_params`
    # (a different RNG algorithm than jax.random).
    params = GraphParams(
        Dict(
            "x" => NodeParams(
                Dict{String, Matrix{Float32}}(), Dict{String, Matrix{Float32}}()
            ),
            "h" => NodeParams(
                Dict(edge_xh => FIX_C["params0_h_w__$(edge_xh)"]),
                Dict("b" => FIX_C["params0_h_b__b"])
            ),
            "y" => NodeParams(
                Dict(edge_hy => FIX_C["params0_y_w__$(edge_hy)"]),
                Dict("b" => FIX_C["params0_y_b__b"])
            )
        )
    )

    Xb = FIX_C["batch_x"]
    Yb = FIX_C["batch_y"]
    clamps = Dict{String, Any}("x" => Xb, "y" => Yb)

    # STATE-INIT RNG NON-ISSUE (see generate_tier_c_fixtures.py's docstring): "x" is the sole
    # in_degree=0 node in this graph and is always clamped below, so the rng argument to
    # `initialize_graph_state` never affects a single compared output array -- any concrete
    # `AbstractRNG` is fine here (no seed-reproducibility claim needed, unlike params/batch
    # above, which ARE the genuine RNG trap).
    rng = Random.default_rng()

    init_state = initialize_graph_state(structure, B, rng; clamps=clamps, params=params)

    @testset "initialize_graph_state (vs upstream initialize_graph_state)" begin
        check_tier_c_state("init", init_state)
    end

    @testset "one inference_step (vs upstream InferenceSGD.inference_step)" begin
        state1 = inference_step(params, init_state, clamps, structure)
        check_tier_c_state("step1", state1)
    end

    converged = run_inference(params, init_state, clamps, structure)

    @testset "run_inference to convergence (vs upstream run_inference, 8 steps)" begin
        check_tier_c_state("converged", converged)
    end

    batch = Dict{String, Any}("x" => Xb, "y" => Yb)
    grads, energy, grad_final_state = get_graph_param_gradient(
        params, batch, structure, rng
    )

    @testset "get_graph_param_gradient (vs upstream, own re-init from batch)" begin
        check_tier_c_params("grad", grads, edge_xh, edge_hy)
        @test allclose_c([Float32(energy)], FIX_C["scalars_energy_pretrain"])
        check_tier_c_state("grad_final", grad_final_state)
    end

    @testset "one train_step (vs upstream optax.sgd, lr=0.05)" begin
        LR = 0.05
        new_params, energy2, final_state2 = train_step(params, batch, structure, LR, rng)
        check_tier_c_params("trained", new_params, edge_xh, edge_hy)
        @test allclose_c([Float32(energy2)], FIX_C["scalars_energy_trainstep"])
        check_tier_c_state("trained_final", final_state2)
    end
end
