# Tier B conformance (docs/AUDIT_REGISTER.md section 6): node-local -- per-node forward +
# BOTH gradient paths (closed-form and/or the Phase-D autodiff seam) vs the pinned upstream
# JAX FabricPC checkout, rtol/atol 1e-5. Fixtures generated by
# scripts/generate_tier_b_fixtures.py into fixtures/tier_b.npz.
#
# Drafted by a 6-way parallel research workflow (one agent per node group: Linear+
# LinearResidual, IdentityNode+SkipConnection, TransformerBlock, MhaResidualNode+
# LnMlp1Node+Mlp2ResidualNode, EmbeddingNode+VocabProjectionNode, StorkeyHopfield), each
# reading both the upstream Python node class and the Julia node implementation directly
# and self-testing its own fixture-generation code against the real venv before returning
# it -- assembled and Julia-verified by hand afterward (see git log).
using Test
using NPZ
using FabricPC
using Zygote                                   # Phase-D autodiff seam (NOT Enzyme -- F-04:
# only one AD backend per session; Enzyme
# aborts on TransformerBlock's MHA block)
import FabricPC: forward, forward_and_weight_grads, forward_and_latent_grads

const FIX_B = npzread(joinpath(@__DIR__, "fixtures", "tier_b.npz"))

# numpy.allclose semantics, Tier B's own (looser) tolerance -- separate name from Tier A's
# `allclose`/`FIX`/`RTOL`/`ATOL` (test_tier_a.jl, already `include`d earlier in runtests.jl
# and sharing this file's Main scope) so neither tier's constants shadow the other's.
allclose_b(a, b; rtol=1.0f-5, atol=1.0f-5) = all(abs.(a .- b) .<= atol .+ rtol .* abs.(b))


# ==============================================================================
# Node group: linear_family
# ==============================================================================
# REQUIRED_IMPORTS: import FabricPC: forward, forward_and_latent_grads, forward_and_weight_grads
# (Linear/LinearResidual's node-level `forward`, `forward_and_latent_grads`,
# `forward_and_weight_grads` are NOT exported by FabricPC.jl -- grep-verified against
# `export` statements in src/FabricPC.jl. `initialize_params`, `NodeParams`, `NodeState`,
# `NodeInfo`, `SlotInfo`, `Linear`, `LinearResidual`, `GaussianEnergy`, `IdentityActivation`
# ARE exported and already in scope via `using FabricPC`. Hoist the import line above to
# file-top (it cannot live inside the @testset block below).

@testset "Tier B: Linear + LinearResidual (closed-form gradients, upstream JAX)" begin
    @testset "Linear (vs upstream LinearExplicitGrad): forward + weight grads + latent grads" begin
        node = Linear((5,), "linear")  # default activation=Identity, energy=Gaussian
        edge_key = "x->linear:in"

        x = FIX_B["linear_fwd_x"]
        W = FIX_B["linear_fwd_W"]
        b = FIX_B["linear_fwd_b"]
        zlat = FIX_B["linear_fwd_z_latent"]
        B, OUT = size(zlat)

        # RNG TRAP: params built DIRECTLY from the fixture's arrays, never via
        # node's own initialize_params (that would use Julia's RNG, not jax.random).
        params = NodeParams(Dict(edge_key => W), Dict("b" => b))
        inputs = Dict{String, Any}(edge_key => x)
        st = NodeState(
            zlat, zeros(Float32, B, OUT), zeros(Float32, B, OUT),
            zeros(Float32, B), zeros(Float32, B, OUT)
        )
        # NodeInfo: in_degree=1, out_degree=1 (matches the Python fixture's info) so
        # forward_and_latent_grads lands in the "internal/clamped" branch on both sides.
        info = NodeInfo(
            "linear", (OUT,), "Linear", Dict{String, SlotInfo}(),
            1, 1, [edge_key], String[], nothing
        )

        ns = forward(node, params, inputs, st)
        @test allclose_b(ns.z_mu, FIX_B["linear_fwd_z_mu"])
        @test allclose_b(ns.error, FIX_B["linear_fwd_error"])
        @test allclose_b(ns.energy, FIX_B["linear_fwd_energy"])

        _, gp = forward_and_weight_grads(node, params, inputs, st)
        @test allclose_b(gp.weights[edge_key], FIX_B["linear_gradw_W"])
        @test allclose_b(gp.biases["b"], FIX_B["linear_gradw_b"])

        _, in_grads, self_grad = forward_and_latent_grads(
            node, params, inputs, st, info, true
        )
        @test allclose_b(in_grads[edge_key], FIX_B["linear_gradz_x"])
        @test allclose_b(self_grad, FIX_B["linear_gradz_self_grad"])
    end

    @testset "LinearResidual (vs upstream autodiff ground truth): forward + weight grads + latent grads" begin
        # Upstream LinearResidual has NO explicit-grad override (only forward()) -- its
        # forward_and_latent_grads/forward_and_weight_grads fall through to NodeBase's
        # jax.value_and_grad autodiff defaults. Julia's LinearResidual IS the fused
        # closed-form path, so this fixture checks Julia's hand-derived closed form
        # against jax autodiff ground truth of the SAME forward() math -- same rationale
        # Tier A used for grad_mu (see generate_tier_a_fixtures.py docstring), not a
        # transcription of an upstream closed form (none exists for this node).
        node_r = LinearResidual((5,), "linresid")
        edge_in_r = "a->linresid:in"
        edge_skip_r = "b->linresid:skip"

        xr = FIX_B["linresid_fwd_x"]
        Wr = FIX_B["linresid_fwd_W"]
        br = FIX_B["linresid_fwd_b"]
        xskip = FIX_B["linresid_fwd_skip"]
        zlat_r = FIX_B["linresid_fwd_z_latent"]
        Br, OUTr = size(zlat_r)

        params_r = NodeParams(Dict(edge_in_r => Wr), Dict("b" => br))
        inputs_r = Dict{String, Any}(edge_in_r => xr, edge_skip_r => xskip)
        st_r = NodeState(
            zlat_r, zeros(Float32, Br, OUTr), zeros(Float32, Br, OUTr),
            zeros(Float32, Br), zeros(Float32, Br, OUTr)
        )
        info_r = NodeInfo(
            "linresid", (OUTr,), "LinearResidual", Dict{String, SlotInfo}(),
            2, 1, [edge_in_r, edge_skip_r], String[], nothing
        )

        ns_r = forward(node_r, params_r, inputs_r, st_r)
        @test allclose_b(ns_r.z_mu, FIX_B["linresid_fwd_z_mu"])
        @test allclose_b(ns_r.error, FIX_B["linresid_fwd_error"])
        @test allclose_b(ns_r.energy, FIX_B["linresid_fwd_energy"])

        _, gp_r = forward_and_weight_grads(node_r, params_r, inputs_r, st_r)
        @test allclose_b(gp_r.weights[edge_in_r], FIX_B["linresid_gradw_W"])
        @test allclose_b(gp_r.biases["b"], FIX_B["linresid_gradw_b"])

        _, in_grads_r, self_grad_r = forward_and_latent_grads(
            node_r, params_r, inputs_r, st_r, info_r, true
        )
        @test allclose_b(in_grads_r[edge_in_r], FIX_B["linresid_gradz_x"])
        @test allclose_b(in_grads_r[edge_skip_r], FIX_B["linresid_gradz_skip"])
        @test allclose_b(self_grad_r, FIX_B["linresid_gradz_self_grad"])
    end
end

# ==============================================================================
# Node group: identity_skip
# ==============================================================================
# REQUIRED_IMPORTS (hoist to file-top, outside any @testset):
# import FabricPC: forward, forward_and_latent_grads, forward_and_weight_grads

@testset "Tier B: IdentityNode + SkipConnection (closed-form grads, isolated node-level)" begin
    @testset "IdentityNode" begin
        x1 = FIX_B["identity_skip_identity_fwd_x1"]
        x2 = FIX_B["identity_skip_identity_fwd_x2"]
        z_latent = FIX_B["identity_skip_identity_fwd_z_latent"]
        scale = FIX_B["identity_skip_identity_fwd_scale"][1]

        B = size(x1, 1)
        Dshape = size(x1)[2:end]
        node = IdentityNode(Dshape, "id"; scale=Float32(scale))
        params = NodeParams(
            Dict{String, Matrix{Float32}}(), Dict{String, Matrix{Float32}}()
        )
        inputs = Dict{String, Any}("e1" => x1, "e2" => x2)
        state = NodeState(
            z_latent, zeros(Float32, size(x1)...), zeros(Float32, size(x1)...),
            zeros(Float32, B), zeros(Float32, size(x1)...)
        )

        # forward
        ns = forward(node, params, inputs, state)
        total_energy = sum(ns.energy)
        @test allclose_b([total_energy], FIX_B["identity_skip_identity_fwd_energy"])
        @test allclose_b(ns.z_mu, FIX_B["identity_skip_identity_fwd_z_mu"])
        @test allclose_b(ns.error, FIX_B["identity_skip_identity_fwd_error"])
        # forward_and_latent_grads: general branch (in_degree=2>0, out_degree=1>0)
        # -- matches upstream's autodiff "else" branch in NodeBase.forward_and_latent_grads.
        info = NodeInfo(
            "id", Dshape, "IdentityNode", Dict{String, SlotInfo}(),
            2, 1, ["e1", "e2"], String["id->out:in"], nothing
        )
        ns_g, input_grads, self_grad = forward_and_latent_grads(
            node, params, inputs, state, info, false
        )
        @test allclose_b(input_grads["e1"], FIX_B["identity_skip_identity_gradz_e1_grad"])
        @test allclose_b(input_grads["e2"], FIX_B["identity_skip_identity_gradz_e2_grad"])
        @test allclose_b(self_grad, FIX_B["identity_skip_identity_gradz_self_grad"])
        @test allclose_b(ns_g.energy, FIX_B["identity_skip_identity_gradz_energy"])
        @test allclose_b(ns_g.z_mu, FIX_B["identity_skip_identity_gradz_z_mu"])

        # forward_and_weight_grads: no learnable params on either side -> grads
        # are structurally always empty; only the returned state's per-sample
        # energy has fixture data to compare.
        ns_w, params_grad = forward_and_weight_grads(node, params, inputs, state)
        @test length(params_grad.weights) == 0
        @test length(params_grad.biases) == 0
        @test allclose_b(ns_w.energy, FIX_B["identity_skip_identity_gradw_energy"])
    end

    @testset "SkipConnection" begin
        y1 = FIX_B["identity_skip_skip_fwd_x1"]
        y2 = FIX_B["identity_skip_skip_fwd_x2"]
        z_latent_s = FIX_B["identity_skip_skip_fwd_z_latent"]

        Bs = size(y1, 1)
        Dshape_s = size(y1)[2:end]
        node_s = SkipConnection(Dshape_s, "skip")
        params_s = NodeParams(
            Dict{String, Matrix{Float32}}(), Dict{String, Matrix{Float32}}()
        )
        inputs_s = Dict{String, Any}("f1" => y1, "f2" => y2)
        state_s = NodeState(
            z_latent_s, zeros(Float32, size(y1)...), zeros(Float32, size(y1)...),
            zeros(Float32, Bs), zeros(Float32, size(y1)...)
        )

        ns_s = forward(node_s, params_s, inputs_s, state_s)
        total_energy_s = sum(ns_s.energy)
        @test allclose_b([total_energy_s], FIX_B["identity_skip_skip_fwd_energy"])
        @test allclose_b(ns_s.z_mu, FIX_B["identity_skip_skip_fwd_z_mu"])
        @test allclose_b(ns_s.error, FIX_B["identity_skip_skip_fwd_error"])
        info_s = NodeInfo(
            "skip", Dshape_s, "SkipConnection", Dict{String, SlotInfo}(),
            2, 1, ["f1", "f2"], String["skip->out:in"], nothing
        )
        ns_g_s, input_grads_s, self_grad_s = forward_and_latent_grads(
            node_s, params_s, inputs_s, state_s, info_s, false
        )
        @test allclose_b(input_grads_s["f1"], FIX_B["identity_skip_skip_gradz_f1_grad"])
        @test allclose_b(input_grads_s["f2"], FIX_B["identity_skip_skip_gradz_f2_grad"])
        @test allclose_b(self_grad_s, FIX_B["identity_skip_skip_gradz_self_grad"])
        @test allclose_b(ns_g_s.energy, FIX_B["identity_skip_skip_gradz_energy"])
        @test allclose_b(ns_g_s.z_mu, FIX_B["identity_skip_skip_gradz_z_mu"])

        ns_w_s, params_grad_s = forward_and_weight_grads(
            node_s, params_s, inputs_s, state_s
        )
        @test length(params_grad_s.weights) == 0
        @test length(params_grad_s.biases) == 0
        @test allclose_b(ns_w_s.energy, FIX_B["identity_skip_skip_gradw_energy"])
    end
end


# ==============================================================================
# Node group: transformer_block
# ==============================================================================
# REQUIRED_IMPORTS (hoist to file top, before any @testset block — imports cannot
# live inside a @testset):
#   using Zygote
#   import FabricPC: forward, forward_and_weight_grads, forward_and_latent_grads
# (TransformerBlock, compute_mu, NodeParams, NodeState, NodeInfo, SlotInfo,
#  MuPCScalingFactors are all already exported by FabricPC — no import needed.)
# `using Zygote` is REQUIRED (not Enzyme) for the plain forward_and_latent_grads
# case below: autodiff.jl's comments state Enzyme aborts on TransformerBlock's
# multi-head-attention block ("addToDiffe: unhandled accumulate with partial
# sizes"), Zygote is the working backend for this node family.

@testset "Tier B: TransformerBlock (forward + both grad paths; muPC F-01 re-validation vs upstream)" begin
    B, S, E, H = 2, 4, 8, 2
    edge_key = "x->tb:in"
    node = TransformerBlock((S, E), "tb"; num_heads=H)   # causal=false, ff_dim=4E default (matches fixture)

    weights = Dict{String, Any}(
        "W_q" => FIX_B["tb_shared_w_W_q"], "W_k" => FIX_B["tb_shared_w_W_k"],
        "W_v" => FIX_B["tb_shared_w_W_v"], "W_o" => FIX_B["tb_shared_w_W_o"],
        "W_ff1" => FIX_B["tb_shared_w_W_ff1"], "W_ff2" => FIX_B["tb_shared_w_W_ff2"],
        "ln1_gamma" => FIX_B["tb_shared_w_ln1_gamma"],
        "ln2_gamma" => FIX_B["tb_shared_w_ln2_gamma"]
    )
    biases = Dict{String, Any}(
        "b_q" => FIX_B["tb_shared_b_b_q"], "b_k" => FIX_B["tb_shared_b_b_k"],
        "b_v" => FIX_B["tb_shared_b_b_v"], "b_o" => FIX_B["tb_shared_b_b_o"],
        # b_ff1 MUST be reshaped to 2D (1,ff_dim): compute_mu derives its reshape target
        # via `size(params.biases["b_ff1"], 2)` (transformer.jl), unlike every other
        # bias/gamma/beta here which reshape via a FIXED literal E and so tolerate the
        # raw (1,1,E) fixture shape as-is. Left as (1,1,32), size(...,2)==1 (not 32) and
        # compute_mu's own reshape errors outright (DimensionMismatch) — verified by
        # running this exact case before adding the reshape below.
        "b_ff1" => reshape(FIX_B["tb_shared_b_b_ff1"], 1, :),
        "b_ff2" => FIX_B["tb_shared_b_b_ff2"],
        "ln1_beta" => FIX_B["tb_shared_b_ln1_beta"],
        "ln2_beta" => FIX_B["tb_shared_b_ln2_beta"]
    )
    # NOTE: gamma/beta/b_q/b_k/b_v/b_o/b_ff2/ln*_beta fixture arrays are (1,1,E) as
    # dumped by upstream; NodeParams accepts them as-is — _tb_dense/_tb_layernorm
    # reshape internally to (1,1,E) via a fixed literal E regardless of the stored
    # array's original ndims (reshape only needs the element count to match). b_ff1 is
    # the one exception (see comment above).
    params = NodeParams(weights, biases)

    x = FIX_B["tb_shared_x"]
    zlat = FIX_B["tb_shared_zlatent"]
    inputs = Dict{String, Any}(edge_key => x)
    st = NodeState(
        zlat, zeros(Float32, B, S, E), zeros(Float32, B, S, E),
        zeros(Float32, B), zeros(Float32, B, S, E)
    )

    @testset "forward: compute_mu vs upstream" begin
        zmu = compute_mu(node, params, inputs)
        @test allclose_b(zmu, FIX_B["tb_muPCoff_zmu"]; rtol=1.0f-5, atol=1.0f-5)
    end

    info_off = NodeInfo(
        "tb", (S, E), "TransformerBlock", Dict{String, SlotInfo}(),
        1, 1, [edge_key], String[], nothing
    )

    @testset "forward_and_weight_grads: muPC OFF (negative control, unscaled)" begin
        _, gp_off = forward_and_weight_grads(node, params, inputs, st; info=info_off)
        for k in keys(gp_off.weights)
            @test allclose_b(
                gp_off.weights[k], FIX_B["tb_muPCoff_gradw_$k"]; rtol=1.0f-5, atol=1.0f-5
            )
        end
        for k in keys(gp_off.biases)
            # vec(...) both sides: b_ff1's gradient is (1,32) (matches its reshaped
            # param above) but the fixture stores it as raw (1,1,32) — flatten sidesteps
            # the shape mismatch (same 32 values either way, no reordering across two
            # singleton dims). Every other bias key is unaffected (vec of an
            # already-matching shape is a no-op for the comparison).
            @test allclose_b(
                vec(gp_off.biases[k]), vec(FIX_B["tb_muPCoff_gradw_$k"]); rtol=1.0f-5,
                atol=1.0f-5
            )
        end
    end

    @testset "forward_and_weight_grads: muPC ON (a=2.5, LayerNorm compensation, F-01)" begin
        a = 2.5f0
        sc = MuPCScalingFactors(
            Dict(edge_key => a), 1.0f0, Dict(edge_key => a), Dict(edge_key => 1.0f0)
        )
        info_on = NodeInfo(
            "tb", (S, E), "TransformerBlock", Dict{String, SlotInfo}(),
            1, 1, [edge_key], String[], sc
        )
        _, gp_on = forward_and_weight_grads(node, params, inputs, st; info=info_on)
        _, gp_off = forward_and_weight_grads(node, params, inputs, st; info=info_off)

        for k in keys(gp_on.weights)
            @test allclose_b(
                gp_on.weights[k], FIX_B["tb_muPCon_gradw_$k"]; rtol=1.0f-5, atol=1.0f-5
            )
            @test allclose_b(
                gp_on.weights[k], a .* gp_off.weights[k]; rtol=1.0f-5, atol=1.0f-5
            )
        end
        for k in keys(gp_on.biases)
            @test allclose_b(
                vec(gp_on.biases[k]), vec(FIX_B["tb_muPCon_gradw_$k"]); rtol=1.0f-5,
                atol=1.0f-5
            )
            # asymmetry independently re-confirmed against REAL upstream numbers:
            # biases are NOT scaled by `a` (transformer.py:392-422 only rescales
            # params_grad.weights, leaves params_grad.biases untouched).
            @test allclose_b(gp_on.biases[k], gp_off.biases[k]; rtol=1.0f-6, atol=1.0f-6)
        end
    end

    @testset "forward_and_latent_grads: plain generic seam (no override)" begin
        ns, input_grads, self_grad = forward_and_latent_grads(
            node, params, inputs, st, info_off, false   # is_clamped=false; info_off has scaling_config=nothing (irrelevant here: "muPC scaling is NOT applied" in this seam per both languages' docstrings)
        )
        @test allclose_b(ns.z_mu, FIX_B["tb_latentgrad_zmu"]; rtol=1.0f-5, atol=1.0f-5)
        @test allclose_b(
            input_grads[edge_key], FIX_B["tb_latentgrad_dinput"]; rtol=1.0f-5, atol=1.0f-5
        )
        @test allclose_b(self_grad, FIX_B["tb_latentgrad_dself"]; rtol=1.0f-5, atol=1.0f-5)
    end

    @testset "T2: causal vs full forward + future-position invariance" begin
        node_causal = TransformerBlock((S, E), "tb_causal"; num_heads=H, causal=true)
        node_full = TransformerBlock((S, E), "tb_full"; num_heads=H, causal=false)

        x_base = FIX_B["tb_t2_x_base"]
        x_pert = FIX_B["tb_t2_x_pert"]   # differs from x_base ONLY at the LAST (future) seq position
        in_base = Dict{String, Any}(edge_key => x_base)
        in_pert = Dict{String, Any}(edge_key => x_pert)

        causal_out_base = compute_mu(node_causal, params, in_base)
        causal_out_pert = compute_mu(node_causal, params, in_pert)
        full_out_base = compute_mu(node_full, params, in_base)
        full_out_pert = compute_mu(node_full, params, in_pert)

        # byte-level conformance vs upstream
        @test allclose_b(
            causal_out_base, FIX_B["tb_t2_causal_out_base"]; rtol=1.0f-5, atol=1.0f-5
        )
        @test allclose_b(
            causal_out_pert, FIX_B["tb_t2_causal_out_pert"]; rtol=1.0f-5, atol=1.0f-5
        )
        @test allclose_b(
            full_out_base, FIX_B["tb_t2_full_out_base"]; rtol=1.0f-5, atol=1.0f-5
        )
        @test allclose_b(
            full_out_pert, FIX_B["tb_t2_full_out_pert"]; rtol=1.0f-5, atol=1.0f-5
        )

        # PROPERTY check (not just fixture-value): causal position 1 (1-based ==
        # upstream position 0) is EXACTLY invariant to a perturbation of the last
        # (future) position — the causal mask sets that key's score to -1e9,
        # exp() underflows to exactly 0.0f0 in Float32, so the future value's
        # contribution is exactly zero, not merely small. Full (non-causal)
        # attention has no such exclusion and must visibly change (confirmed
        # upstream: max|diff| ≈ 1.25 vs exactly 0.0 for causal — see self-test).
        @test causal_out_base[:, 1, :] == causal_out_pert[:, 1, :]
        @test maximum(abs.(full_out_base[:, 1, :] .- full_out_pert[:, 1, :])) > 1.0f-3
    end
end


# ==============================================================================
# Node group: decomposed_mha_mlp
# ==============================================================================
# REQUIRED_IMPORTS (hoist to file top, alongside the existing `using FabricPC` / `using NPZ`):
#   using Zygote                                            # activates the Phase-D autodiff seam
#   import FabricPC: forward, forward_and_weight_grads, forward_and_latent_grads
#   # (compute_mu, NodeParams, NodeState, NodeInfo, SlotInfo, MhaResidualNode, LnMlp1Node,
#   #  Mlp2ResidualNode are already exported by `using FabricPC` -- no import needed for those.)
#   # `FIX` (loaded fixture Dict) and `allclose_b(a,b)` are assumed already in scope per
#   # test_tier_a.jl's pattern.

@testset "Tier B: decomposed_mha_mlp (MhaResidualNode / LnMlp1Node / Mlp2ResidualNode)" begin
    # Fixture arrays store 1D bias/gamma vectors (upstream shape (E,)); Julia's own
    # initialize_params always builds these as (1,n) row matrices (see MhaResidualNode's/
    # LnMlp1Node's initialize_params in transformer_decomposed.jl) -- reshape to match that
    # convention. compute_mu itself only cares about total element count for ln_gamma/ln_beta/
    # b_q/b_k/b_v/b_o (reshaped via an explicit `E` it derives from `x`), but LnMlp1Node's
    # b_ff1 and Mlp2ResidualNode's b_ff2 are reshaped via `size(bias, 2)` inside compute_mu --
    # THOSE MUST be real (1,n) 2D matrices or that reshape silently computes the wrong size.
    row(v) = reshape(Float32.(v), 1, :)

    @testset "MhaResidualNode: forward + weight grads + latent grads" begin
        P = "dmm_mha_fwd_"
        weights = Dict(
            "ln_gamma" => row(FIX_B[P * "ln_gamma"]), "W_q" => Float32.(FIX_B[P * "W_q"]),
            "W_k" => Float32.(FIX_B[P * "W_k"]), "W_v" => Float32.(FIX_B[P * "W_v"]),
            "W_o" => Float32.(FIX_B[P * "W_o"])
        )
        biases = Dict(
            "ln_beta" => row(FIX_B[P * "ln_beta"]), "b_q" => row(FIX_B[P * "b_q"]),
            "b_k" => row(FIX_B[P * "b_k"]), "b_v" => row(FIX_B[P * "b_v"]),
            "b_o" => row(FIX_B[P * "b_o"])
        )
        params = NodeParams(weights, biases)
        x = Float32.(FIX_B[P * "x"])
        skip = Float32.(FIX_B[P * "skip"])
        B, S, E = size(x)
        inputs = Dict{String, Any}("x->mha:in" => x, "skip->mha:skip" => skip)
        node = MhaResidualNode((S, E), "mha"; num_heads=2, use_rope=true, causal=true)

        # --- forward: z_mu ---
        z = compute_mu(node, params, inputs)
        @test allclose_b(z, FIX_B[P * "out"])

        # --- weight grads (learning phase, no muPC scaling: info kwarg omitted) ---
        GW = "dmm_mha_gradw_"
        zlat = Float32.(FIX_B[GW * "z_latent"])
        st = NodeState(
            zlat, zeros(Float32, B, S, E), zeros(Float32, B, S, E),
            zeros(Float32, B), zeros(Float32, B, S, E)
        )
        _, gp = forward_and_weight_grads(node, params, inputs, st)
        @test allclose_b(gp.weights["W_q"], FIX_B[GW * "gW_q"])
        @test allclose_b(gp.weights["W_k"], FIX_B[GW * "gW_k"])
        @test allclose_b(gp.weights["W_v"], FIX_B[GW * "gW_v"])
        @test allclose_b(gp.weights["W_o"], FIX_B[GW * "gW_o"])
        @test allclose_b(gp.weights["ln_gamma"], row(FIX_B[GW * "gln_gamma"]))
        @test allclose_b(gp.biases["b_q"], row(FIX_B[GW * "gb_q"]))
        @test allclose_b(gp.biases["b_k"], row(FIX_B[GW * "gb_k"]))
        @test allclose_b(gp.biases["b_v"], row(FIX_B[GW * "gb_v"]))
        @test allclose_b(gp.biases["b_o"], row(FIX_B[GW * "gb_o"]))
        @test allclose_b(gp.biases["ln_beta"], row(FIX_B[GW * "gln_beta"]))

        # --- latent grads (inference phase): both "in" and "skip" edges + self_grad ---
        GL = "dmm_mha_gradlatent_"
        info = NodeInfo(
            "mha", (S, E), "MhaResidualNode", Dict{String, SlotInfo}(),
            2, 1, collect(keys(inputs)), String[], nothing
        )
        _, igrads, sg = forward_and_latent_grads(node, params, inputs, st, info, false)
        @test allclose_b(igrads["x->mha:in"], FIX_B[GL * "grad_in"])
        @test allclose_b(igrads["skip->mha:skip"], FIX_B[GL * "grad_skip"])
        @test allclose_b(sg, FIX_B[GL * "self_grad"])
    end

    @testset "LnMlp1Node: forward + weight grads + latent grads" begin
        P = "dmm_lnmlp1_fwd_"
        weights = Dict(
            "ln_gamma" => row(FIX_B[P * "ln_gamma"]),
            "W_ff1" => Float32.(FIX_B[P * "W_ff1"])
        )
        biases = Dict(
            "ln_beta" => row(FIX_B[P * "ln_beta"]), "b_ff1" => row(FIX_B[P * "b_ff1"])
        )
        params = NodeParams(weights, biases)
        x = Float32.(FIX_B[P * "x"])
        B, S, E = size(x)
        ff = size(weights["W_ff1"], 2)
        inputs = Dict{String, Any}("mha->mlp1:in" => x)
        node = LnMlp1Node((S, ff), "mlp1")   # default activation = GeluActivation(), matches upstream default

        z = compute_mu(node, params, inputs)
        @test allclose_b(z, FIX_B[P * "out"])
        @test size(z) == (B, S, ff)

        GW = "dmm_lnmlp1_gradw_"
        zlat = Float32.(FIX_B[GW * "z_latent"])
        st = NodeState(
            zlat, zeros(Float32, B, S, ff), zeros(Float32, B, S, ff),
            zeros(Float32, B), zeros(Float32, B, S, ff)
        )
        _, gp = forward_and_weight_grads(node, params, inputs, st)
        @test allclose_b(gp.weights["W_ff1"], FIX_B[GW * "gW_ff1"])
        @test allclose_b(gp.weights["ln_gamma"], row(FIX_B[GW * "gln_gamma"]))
        @test allclose_b(gp.biases["b_ff1"], row(FIX_B[GW * "gb_ff1"]))
        @test allclose_b(gp.biases["ln_beta"], row(FIX_B[GW * "gln_beta"]))

        GL = "dmm_lnmlp1_gradlatent_"
        info = NodeInfo(
            "mlp1", (S, ff), "LnMlp1Node", Dict{String, SlotInfo}(),
            1, 1, collect(keys(inputs)), String[], nothing
        )
        _, igrads, sg = forward_and_latent_grads(node, params, inputs, st, info, false)
        @test allclose_b(igrads["mha->mlp1:in"], FIX_B[GL * "grad_in"])
        @test allclose_b(sg, FIX_B[GL * "self_grad"])
    end

    @testset "Mlp2ResidualNode: multi-slot forward + weight grads + latent grads" begin
        P = "dmm_mlp2_fwd_"
        weights = Dict("W_ff2" => Float32.(FIX_B[P * "W_ff2"]))
        biases = Dict("b_ff2" => row(FIX_B[P * "b_ff2"]))
        params = NodeParams(weights, biases)
        mlp1 = Float32.(FIX_B[P * "mlp1"])
        res = Float32.(FIX_B[P * "residual"])
        B, S, ff = size(mlp1)
        E = size(res, 3)
        inputs = Dict{String, Any}("m1->mlp2:in" => mlp1, "mha->mlp2:residual" => res)
        node = Mlp2ResidualNode((S, E), "mlp2")

        z = compute_mu(node, params, inputs)
        @test allclose_b(z, FIX_B[P * "out"])
        @test size(z) == (B, S, E)

        GW = "dmm_mlp2_gradw_"
        zlat = Float32.(FIX_B[GW * "z_latent"])
        st = NodeState(
            zlat, zeros(Float32, B, S, E), zeros(Float32, B, S, E),
            zeros(Float32, B), zeros(Float32, B, S, E)
        )
        _, gp = forward_and_weight_grads(node, params, inputs, st)
        @test allclose_b(gp.weights["W_ff2"], FIX_B[GW * "gW_ff2"])
        @test allclose_b(gp.biases["b_ff2"], row(FIX_B[GW * "gb_ff2"]))

        GL = "dmm_mlp2_gradlatent_"
        info = NodeInfo(
            "mlp2", (S, E), "Mlp2ResidualNode", Dict{String, SlotInfo}(),
            2, 1, collect(keys(inputs)), String[], nothing
        )
        _, igrads, sg = forward_and_latent_grads(node, params, inputs, st, info, false)
        @test haskey(igrads, "m1->mlp2:in") && haskey(igrads, "mha->mlp2:residual")
        @test allclose_b(igrads["m1->mlp2:in"], FIX_B[GL * "grad_in"])
        @test allclose_b(igrads["mha->mlp2:residual"], FIX_B[GL * "grad_residual"])
        @test allclose_b(sg, FIX_B[GL * "self_grad"])
    end
end

# ==============================================================================
# Node group: embedding_vocab
# ==============================================================================
# REQUIRED_IMPORTS (hoist to file top, before this testset -- cannot live inside a
# @testset block):
#   import FabricPC: forward, forward_and_weight_grads, forward_and_latent_grads
#   using Zygote
# `forward`/`forward_and_weight_grads`/`forward_and_latent_grads` are NOT in
# FabricPC.jl's export list (grep '^export' confirmed) -- test_transformer.jl /
# test_transformer_decomposed.jl access them via a module alias (`const TF =
# FabricPC; TF.forward_and_weight_grads(...)`); this snippet instead imports the
# three names directly so the testset body can call them unqualified, matching
# test_tier_a.jl's `import FabricPC: _tb_layernorm, ...` convention.
# `using Zygote` activates the Phase-D autodiff seam (nodes/autodiff.jl) that
# VocabProjectionNode's forward_and_weight_grads/forward_and_latent_grads need
# (it only implements compute_mu, no explicit gradient overrides) -- EmbeddingNode's
# own overrides are bespoke and do NOT need an AD backend. Per F-04
# (docs/AUDIT_REGISTER.md), do NOT also `using Enzyme` in the same Julia session --
# the two backends silently clobber each other's dispatch.
# NOTE ON TOLERANCE: this repo's Tier A harness (test/conformance/test_tier_a.jl)
# defines `allclose_b(a,b; rtol=RTOL, atol=ATOL)` with module-level RTOL=ATOL=1f-6;
# per this task's spec, Tier B fixtures are pinned at rtol/atol 1e-5 (looser --
# VocabProjectionNode's grads route through Zygote AD, not a closed form), so the
# Tier B test file this snippet is hoisted into is assumed to define/override
# RTOL=ATOL=1.0f-5 (or pass rtol=1f-5, atol=1f-5 explicitly per @test) before this
# testset runs; not verified against a live file since Tier B's harness file does
# not exist yet.

@testset "Tier B: EmbeddingNode + VocabProjectionNode (embedding_vocab group)" begin
    # ---------------- EmbeddingNode (bespoke, non-seam path) ----------------
    @testset "EmbeddingNode: forward (token-id lookup)" begin
        idx0 = FIX_B["embedding_vocab_embed_fwd_idx"]           # upstream 0-based ids, (B,S) Int
        idx = Float32.(idx0 .+ 1)                              # Julia: 1-based, Float32-encoded
        embeddings = Float32.(FIX_B["embedding_vocab_embed_fwd_embeddings"])  # SAME table both sides
        z_latent = Float32.(FIX_B["embedding_vocab_embed_fwd_z_latent"])
        B, S, E = size(z_latent)

        node = EmbeddingNode((S, E), "emb"; vocab_size=size(embeddings, 1))
        params = NodeParams(
            Dict("embeddings" => embeddings), Dict{String, Matrix{Float32}}()
        )
        st = NodeState(
            z_latent, zeros(Float32, B, S, E), zeros(Float32, B, S, E),
            zeros(Float32, B), zeros(Float32, B, S, E)
        )
        inputs = Dict{String, Any}("tok->emb:in" => idx)

        ns = forward(node, params, inputs, st)
        @test allclose_b(ns.z_mu, FIX_B["embedding_vocab_embed_fwd_mu"])
        @test allclose_b(ns.energy, FIX_B["embedding_vocab_embed_fwd_energy"])
        @test isapprox(
            sum(ns.energy), Float32(only(FIX_B["embedding_vocab_embed_fwd_total_energy"]));
            rtol=1.0f-5, atol=1.0f-5
        )
    end

    @testset "EmbeddingNode: weight grad (scatter-add by token id)" begin
        idx0 = FIX_B["embedding_vocab_embed_gradw_idx"]
        idx = Float32.(idx0 .+ 1)
        embeddings = Float32.(FIX_B["embedding_vocab_embed_gradw_embeddings"])
        z_latent = Float32.(FIX_B["embedding_vocab_embed_gradw_z_latent"])
        B, S, E = size(z_latent)

        node = EmbeddingNode((S, E), "emb"; vocab_size=size(embeddings, 1))
        params = NodeParams(
            Dict("embeddings" => embeddings), Dict{String, Matrix{Float32}}()
        )
        st = NodeState(
            z_latent, zeros(Float32, B, S, E), zeros(Float32, B, S, E),
            zeros(Float32, B), zeros(Float32, B, S, E)
        )
        inputs = Dict{String, Any}("tok->emb:in" => idx)

        _, gp = forward_and_weight_grads(node, params, inputs, st)
        @test allclose_b(
            gp.weights["embeddings"], FIX_B["embedding_vocab_embed_gradw_gradembeddings"]
        )
    end

    @testset "EmbeddingNode: latent grad (input=0 discrete, self=grad_latent)" begin
        idx0 = FIX_B["embedding_vocab_embed_gradz_idx"]
        idx = Float32.(idx0 .+ 1)
        embeddings = Float32.(FIX_B["embedding_vocab_embed_gradz_embeddings"])
        z_latent = Float32.(FIX_B["embedding_vocab_embed_gradz_z_latent"])
        B, S, E = size(z_latent)

        node = EmbeddingNode((S, E), "emb"; vocab_size=size(embeddings, 1))
        params = NodeParams(
            Dict("embeddings" => embeddings), Dict{String, Matrix{Float32}}()
        )
        st = NodeState(
            z_latent, zeros(Float32, B, S, E), zeros(Float32, B, S, E),
            zeros(Float32, B), zeros(Float32, B, S, E)
        )
        inputs = Dict{String, Any}("tok->emb:in" => idx)
        info = NodeInfo(
            "emb", (S, E), "EmbeddingNode", Dict{String, SlotInfo}(),
            1, 1, ["tok->emb:in"], String[], nothing
        )

        _, ig, sg = forward_and_latent_grads(node, params, inputs, st, info, false)
        @test all(iszero, ig["tok->emb:in"])
        @test allclose_b(sg, FIX_B["embedding_vocab_embed_gradz_selfgrad"])
    end

    # ---------------- VocabProjectionNode (seam-based: compute_mu only) ----------------
    @testset "VocabProjectionNode: forward (Softmax(dense) default + CrossEntropy)" begin
        x = Float32.(FIX_B["embedding_vocab_vocab_fwd_x"])
        W_out = Float32.(FIX_B["embedding_vocab_vocab_fwd_W_out"])
        b_out = Float32.(FIX_B["embedding_vocab_vocab_fwd_b_out"])
        z_latent = Float32.(FIX_B["embedding_vocab_vocab_fwd_z_latent"])   # one-hot targets
        B, S, E = size(x)
        Vout = length(b_out)

        node = VocabProjectionNode((S, Vout), "vocab")   # defaults: Softmax + CrossEntropy
        params = NodeParams(
            Dict("W_out" => W_out), Dict("b_out" => reshape(b_out, 1, Vout))
        )
        st = NodeState(
            z_latent, zeros(Float32, B, S, Vout), zeros(Float32, B, S, Vout),
            zeros(Float32, B), zeros(Float32, B, S, Vout)
        )
        inputs = Dict{String, Any}("h->vocab:in" => x)

        ns = forward(node, params, inputs, st)
        @test allclose_b(ns.z_mu, FIX_B["embedding_vocab_vocab_fwd_mu"])
        @test allclose_b(ns.energy, FIX_B["embedding_vocab_vocab_fwd_energy"])
        @test isapprox(
            sum(ns.energy), Float32(only(FIX_B["embedding_vocab_vocab_fwd_total_energy"]));
            rtol=1.0f-5, atol=1.0f-5
        )
    end

    @testset "VocabProjectionNode: weight grad (Phase-D seam via Zygote)" begin
        x = Float32.(FIX_B["embedding_vocab_vocab_gradw_x"])
        W_out = Float32.(FIX_B["embedding_vocab_vocab_gradw_W_out"])
        b_out = Float32.(FIX_B["embedding_vocab_vocab_gradw_b_out"])
        z_latent = Float32.(FIX_B["embedding_vocab_vocab_gradw_z_latent"])
        B, S, E = size(x)
        Vout = length(b_out)

        node = VocabProjectionNode((S, Vout), "vocab")
        params = NodeParams(
            Dict("W_out" => W_out), Dict("b_out" => reshape(b_out, 1, Vout))
        )
        st = NodeState(
            z_latent, zeros(Float32, B, S, Vout), zeros(Float32, B, S, Vout),
            zeros(Float32, B), zeros(Float32, B, S, Vout)
        )
        inputs = Dict{String, Any}("h->vocab:in" => x)

        _, gp = forward_and_weight_grads(node, params, inputs, st)
        @test allclose_b(
            gp.weights["W_out"], FIX_B["embedding_vocab_vocab_gradw_gradW_out"]
        )
        @test allclose_b(
            vec(gp.biases["b_out"]), FIX_B["embedding_vocab_vocab_gradw_gradb_out"]
        )
    end

    @testset "VocabProjectionNode: latent grad (input + self, Phase-D seam via Zygote)" begin
        x = Float32.(FIX_B["embedding_vocab_vocab_gradz_x"])
        W_out = Float32.(FIX_B["embedding_vocab_vocab_gradz_W_out"])
        b_out = Float32.(FIX_B["embedding_vocab_vocab_gradz_b_out"])
        z_latent = Float32.(FIX_B["embedding_vocab_vocab_gradz_z_latent"])
        B, S, E = size(x)
        Vout = length(b_out)

        node = VocabProjectionNode((S, Vout), "vocab")
        params = NodeParams(
            Dict("W_out" => W_out), Dict("b_out" => reshape(b_out, 1, Vout))
        )
        st = NodeState(
            z_latent, zeros(Float32, B, S, Vout), zeros(Float32, B, S, Vout),
            zeros(Float32, B), zeros(Float32, B, S, Vout)
        )
        inputs = Dict{String, Any}("h->vocab:in" => x)
        info = NodeInfo(
            "vocab", (S, Vout), "VocabProjectionNode", Dict{String, SlotInfo}(),
            1, 1, ["h->vocab:in"], String[], nothing
        )

        _, ig, sg = forward_and_latent_grads(node, params, inputs, st, info, false)
        @test allclose_b(ig["h->vocab:in"], FIX_B["embedding_vocab_vocab_gradz_gradx"])
        @test allclose_b(sg, FIX_B["embedding_vocab_vocab_gradz_selfgrad"])
    end
end


# ==============================================================================
# Node group: storkey
# ==============================================================================
# REQUIRED_IMPORTS (hoist to file top, before any @testset — imports cannot live
# inside a @testset block). `test/conformance/test_tier_a.jl` already provides
# `using FabricPC`, `using NPZ`, `const FIX = npzread(...)`, and the `allclose`
# helper in scope; Tier B additionally needs:
#   import FabricPC: forward, forward_and_weight_grads, forward_and_latent_grads
#   using Zygote   # activates the Phase-D autodiff seam (F-04: exactly ONE of
#                  # Zygote/Enzyme per Julia session — StorkeyHopfield only
#                  # overrides `forward`/`energy_kernel`/`compute_mu`; the two
#                  # gradient methods below are the GENERIC autodiff.jl seam,
#                  # which dispatches to those overrides via multiple dispatch)
# (NodeParams, NodeState, NodeInfo, SlotInfo, StorkeyHopfield, TanhActivation,
#  GaussianEnergy are all already exported by FabricPC — no import needed for those.)

@testset "Tier B: StorkeyHopfield (composite PC + attractor energy) vs upstream JAX" begin
    # Config matches the fixture generator exactly: learnable hopfield_strength
    # (raw scalar lives in params.biases["hopfield_strength"], softplus-constrained
    # inside the node), use_bias=true, enforce_symmetry=true, zero_diagonal=false,
    # activation=Tanh, energy=Gaussian (all upstream + Julia defaults, set explicitly
    # here so the fixture's math and this node's config can never silently drift apart).
    D = 4
    node = StorkeyHopfield(
        (D,), "hop";
        activation=TanhActivation(), energy=GaussianEnergy(),
        hopfield_strength=nothing, use_bias=true,
        enforce_symmetry=true, zero_diagonal=false
    )
    edge_key = "p->hop:in"

    # RNG-trap: build NodeParams DIRECTLY from the fixture's JAX-generated arrays —
    # never call `initialize_params` for the compared values (different RNG family).
    # W is the RAW (unprepared) stored matrix on both sides: `forward`/`compute_mu`
    # re-applies `_prepare_W` every call (idempotent once symmetric), and the
    # gradient w.r.t. this raw matrix already has the symmetrization folded in by
    # autodiff identically on both sides (test_storkey_hopfield.jl's own FD check
    # confirms `dw` comes out symmetric for this reason) — no pre-symmetrization
    # needed when loading the fixture.
    W = Float32.(FIX_B["storkey_fwd_w"])                       # (D, D)
    b = Float32.(FIX_B["storkey_fwd_b"])                        # (1, D)
    s_raw = Float32.(FIX_B["storkey_fwd_s_raw"])                # (1, 1) — Julia's own
    # convention (`_strength` reads `params.biases["hopfield_strength"][1,1]`);
    # upstream stores the SAME scalar VALUE as a 0-d jnp.array (see the Python
    # generator's note) — only the on-disk/in-language shape differs, not the value.
    params = NodeParams(
        Dict(edge_key => W),
        Dict("b" => b, "hopfield_strength" => s_raw)
    )

    probe = Float32.(FIX_B["storkey_fwd_probe"])                # (B, D)
    zlat = Float32.(FIX_B["storkey_fwd_zlat"])                  # (B, D)
    B = size(probe, 1)
    inputs = Dict{String, Any}(edge_key => probe)
    st = NodeState(
        zlat, zeros(Float32, B, D), zeros(Float32, B, D),
        zeros(Float32, B), zeros(Float32, B, D)
    )

    @testset "forward: z_mu, error, per-sample energy, total energy" begin
        ns = forward(node, params, inputs, st)
        tot = sum(ns.energy)
        @test isapprox(
            tot, only(FIX_B["storkey_fwd_total_energy"]); rtol=1.0f-5, atol=1.0f-5
        )
        @test allclose_b(ns.z_mu, FIX_B["storkey_fwd_zmu"]; rtol=1.0f-5, atol=1.0f-5)
        @test allclose_b(ns.error, FIX_B["storkey_fwd_error"]; rtol=1.0f-5, atol=1.0f-5)
        @test allclose_b(ns.energy, FIX_B["storkey_fwd_energy"]; rtol=1.0f-5, atol=1.0f-5)
    end

    @testset "weight grads (learning phase, Phase-D seam via energy_kernel override)" begin
        # Generic `forward_and_weight_grads` (autodiff.jl) — StorkeyHopfield does not
        # override it; it calls the node's own `forward` (full E_pc+E_hop state) then
        # differentiates the node's own `energy_kernel` override w.r.t. `params`
        # (weights AND biases, incl. the raw hopfield_strength scalar), matching
        # upstream's `jax.value_and_grad(node_class.forward, argnums=0, has_aux=True)`.
        _, gp = forward_and_weight_grads(node, params, inputs, st)
        @test allclose_b(
            gp.weights[edge_key], FIX_B["storkey_gradw_dw"]; rtol=1.0f-5, atol=1.0f-5
        )
        @test allclose_b(
            gp.biases["b"], FIX_B["storkey_gradw_db"]; rtol=1.0f-5, atol=1.0f-5
        )
        @test allclose_b(
            reshape(gp.biases["hopfield_strength"], 1, 1), FIX_B["storkey_gradw_ds"];
            rtol=1.0f-5, atol=1.0f-5
        )
    end

    @testset "latent/input grads (inference phase, internal node, is_clamped=false)" begin
        # in_degree=1, out_degree=1 -> the autodiff "else" branch of generic
        # `forward_and_latent_grads`, matching upstream's non-terminal / non-output
        # branch: differentiates the total-energy scalar w.r.t. (inputs, z_latent).
        info = NodeInfo(
            "hop", (D,), "StorkeyHopfield", Dict{String, SlotInfo}(),
            1, 1, [edge_key], String[], nothing
        )
        _, input_grads, self_grad = forward_and_latent_grads(
            node, params, inputs, st, info, false
        )
        @test allclose_b(
            input_grads[edge_key], FIX_B["storkey_gradlatent_dprobe"];
            rtol=1.0f-5, atol=1.0f-5
        )
        @test allclose_b(
            self_grad, FIX_B["storkey_gradlatent_dz"]; rtol=1.0f-5, atol=1.0f-5
        )
    end
end
