# Tier D conformance (docs/AUDIT_REGISTER.md section 6), MNIST-MLP track: END-TO-END -- a
# short real multi-step TRAINING RUN (5 chained train_step calls, each with its own fresh
# batch and 30 inference substeps = 150 inner relaxation iterations total, params/rng
# threaded through sequentially) on a real *assembled graph* x(784)->h(128,tanh)->
# y(10,Identity+Gaussian) (examples/mnist_pc.jl's "plain" non-muPC configuration) -- vs the
# pinned upstream JAX FabricPC checkout. Unlike Tier C (exactly one train_step), this proves
# the whole training loop, not just one step. Fixtures generated by
# scripts/generate_tier_d_mnist_fixtures.py into fixtures/tier_d_mnist.npz (see that script's
# docstring for the RNG-trap note, the NODE-CLASS CHOICE rationale for why "x" uses
# use_bias=false, and the STEP COUNT reasoning for chaining 5 real SGD updates instead of
# Tier C's single step).
using Test
using NPZ
using FabricPC
using Random

const FIX_D = npzread(joinpath(@__DIR__, "fixtures", "tier_d_mnist.npz"))

# numpy.allclose semantics (per-element: |a-b| <= atol + rtol*|b|), NOT Julia's built-in
# array `≈` (a single norm-based check) -- separate name from Tier A/B/C's helpers (already
# `include`d earlier in runtests.jl and sharing this file's Main scope) so no tier's
# helper/constants shadow another's.
#
# TOLERANCE: rtol=atol=1e-4, looser than Tier C's 1e-5. Reason:
#   "Float32 BLAS associativity across multiple inference steps"
# This fixture chains 5 train_step calls x 30 infer_steps = 150 inner relaxation iterations
# with real SGD updates threaded between steps (matmul/sum reduction order can differ
# between XLA and OpenBLAS at each step), so small per-step differences compound across the
# chained trajectory rather than being checked once in isolation, and can legitimately push
# element-wise deltas past Tier C's single-step 1e-5 bound without indicating a real bug.
allclose_d(a, b; rtol=1.0f-4, atol=1.0f-4) = all(abs.(a .- b) .<= atol .+ rtol .* abs.(b))

const TIER_D_NODES = ("x", "h", "y")

"""
    check_tier_d_state(prefix, state)

Assert every dumped `GraphState` field (z_latent/z_mu/error/energy/pre_activation/
latent_grad, per node) for fixture prefix `prefix` (e.g. "final") against the live Julia
`state`.
"""
function check_tier_d_state(prefix::AbstractString, state::GraphState)
    for name in TIER_D_NODES
        ns = state.nodes[name]
        @test allclose_d(ns.z_latent, FIX_D["$(prefix)_$(name)_z_latent"])
        @test allclose_d(ns.z_mu, FIX_D["$(prefix)_$(name)_z_mu"])
        @test allclose_d(ns.error, FIX_D["$(prefix)_$(name)_error"])
        @test allclose_d(ns.energy, FIX_D["$(prefix)_$(name)_energy"])
        @test allclose_d(ns.pre_activation, FIX_D["$(prefix)_$(name)_pre_activation"])
        @test allclose_d(ns.latent_grad, FIX_D["$(prefix)_$(name)_latent_grad"])
    end
end

"""
    check_tier_d_params(prefix, gp, edge_xh, edge_hy)

Assert the dumped `h`/`y` weights + biases for fixture prefix `prefix` (e.g. "params0"/
"final_params") against the live Julia `GraphParams` `gp`. "x" carries no learnable params
(source node, `use_bias=false`) so there is nothing to compare for it.
"""
function check_tier_d_params(
    prefix::AbstractString, gp::GraphParams, edge_xh::AbstractString, edge_hy::AbstractString
)
    @test allclose_d(gp.nodes["h"].weights[edge_xh], FIX_D["$(prefix)_h_w__$(edge_xh)"])
    @test allclose_d(gp.nodes["h"].biases["b"], FIX_D["$(prefix)_h_b__b"])
    @test allclose_d(gp.nodes["y"].weights[edge_hy], FIX_D["$(prefix)_y_w__$(edge_hy)"])
    @test allclose_d(gp.nodes["y"].biases["b"], FIX_D["$(prefix)_y_b__b"])
end

@testset "Tier D conformance (upstream JAX FabricPC, end-to-end, MNIST-MLP, rtol/atol 1e-4)" begin
    B, DX, DH, DY = 8, 784, 128, 10
    N_STEPS = 5
    LR = 0.002

    # NODE-CLASS CHOICE mirrors generate_tier_d_mnist_fixtures.py's rationale exactly (itself
    # mirroring generate_tier_c_fixtures.py's): Julia's `Linear` is the FUSED explicit-grad
    # node (linear.jl: "v0 is autodiff-free ... our node IS the explicit path") -- used for
    # ALL THREE nodes here, matching both the Python side's "x"=Linear (terminal-source
    # special case, use_bias=false) AND "h"/"y"=LinearExplicitGrad (same closed-form math
    # Tier B validated bit-for-bit against Julia's Linear at the isolated-node level, Tier C
    # extended to the loop level; this fixture is the multi-step-trajectory extension of
    # Tier C's single-step case).
    x = Linear((DX,), "x"; use_bias=false)
    h = Linear((DH,), "h"; activation=TanhActivation())
    y = Linear((DY,), "y"; energy=GaussianEnergy())

    inference = InferenceSGD(eta_infer=0.1, infer_steps=30, latent_decay=0.0)
    structure = graph(
        [x, h, y],
        [Edge(x, h), Edge(h, y)],
        TaskMap(x=x, y=y),
        inference
    )

    edge_xh = "x->h:in"
    edge_hy = "h->y:in"

    # RNG TRAP (same as Tier A/B/C, per the generator's docstring): GraphParams built
    # DIRECTLY from the fixture's JAX-generated arrays -- never via Julia's own
    # `initialize_params` (a different RNG algorithm than jax.random). "x" carries NO
    # params at all (use_bias=false; see NODE-CLASS CHOICE above / the generator's
    # docstring for the pytree-mismatch crash this avoids).
    params = GraphParams(
        Dict(
            "x" => NodeParams(
                Dict{String, Matrix{Float32}}(), Dict{String, Matrix{Float32}}()
            ),
            "h" => NodeParams(
                Dict(edge_xh => FIX_D["params0_h_w__$(edge_xh)"]),
                Dict("b" => FIX_D["params0_h_b__b"])
            ),
            "y" => NodeParams(
                Dict(edge_hy => FIX_D["params0_y_w__$(edge_hy)"]),
                Dict("b" => FIX_D["params0_y_b__b"])
            )
        )
    )

    @testset "params0 (vs upstream KaimingInitializer / zero-bias init)" begin
        check_tier_d_params("params0", params, edge_xh, edge_hy)
    end

    # STATE-INIT RNG NON-ISSUE (see generate_tier_d_mnist_fixtures.py's docstring): "x" is
    # the sole in_degree=0 node in this graph, and both task-map nodes ("x" AND "y") are
    # clamped on EVERY train_step call below -- so the rng argument threaded into each call
    # never affects a single compared output array (any concrete `AbstractRNG` is fine here;
    # no cross-language seed-reproducibility claim needed, unlike params0/batches, which ARE
    # the genuine RNG trap).
    rng = Random.default_rng()

    # 5-step training trajectory: fresh fixture batch each step, `params` threaded through
    # sequentially so step i's inference genuinely runs on step (i-1)'s trained weights --
    # matching the generator's STEP COUNT rationale (a params-only or single-step check could
    # not catch a bug that only manifests after several chained SGD updates).
    local final_state
    for i in 1:N_STEPS
        Xb = FIX_D["batch$(i)_x"]
        Yb = FIX_D["batch$(i)_y"]
        batch = Dict{String, Any}("x" => Xb, "y" => Yb)

        params, energy_i, step_final_state = train_step(params, batch, structure, LR, rng)
        final_state = step_final_state

        @testset "train_step $(i)/$(N_STEPS) (vs upstream optax.sgd, lr=$(LR))" begin
            @test allclose_d([Float32(energy_i)], FIX_D["scalars_energy_step$(i)"])
        end
    end

    @testset "final_params after 5 train_steps (vs upstream optax.sgd trajectory)" begin
        check_tier_d_params("final_params", params, edge_xh, edge_hy)
    end

    @testset "final GraphState from the 5th train_step (vs upstream)" begin
        check_tier_d_state("final", final_state)
    end
end
