# Tier D transformer-LM, C-05 NORM-CLIP BOUNDARY-STRADDLE conformance test (2026-07-14).
# Wired into runtests.jl UNGATED alongside test_tier_d_transformer_stable.jl (docs/
# AUDIT_REGISTER.md section 6/C-05) -- promoted after verification, not scratch.
#
# BACKGROUND: test_tier_d_transformer_stable.jl's own InferenceSGDNormClip run (max_norm=1.0,
# vs tier_d_transformer_stable_normclip.npz) passed 523/523 at 1e-4, giving C-05 its first
# conformance-harness coverage -- but a post-hoc check found the actual gradient L2 norms in
# that run never approached max_norm=1.0 anywhere (embed/transformer_0 sat ~0.10-0.27,
# skip_0/output sat ~2.4-33.4): an "all-or-nothing" split with embed/transformer_0 NEVER
# clipping and skip_0/output ALWAYS clipping. The `min(1, max_norm/(norm+eps))` boundary
# branch -- where float32 implementations could plausibly disagree about whether a given
# sample clips -- was never exercised. "Passes" there is coverage BY ABSENCE.
#
# THIS FILE closes that gap against a NEW fixture
# (tier_d_transformer_stable_normclip_boundary.npz, generated by
# scripts/generate_tier_d_transformer_stable_normclip_boundary_fixtures.py) that uses
# max_norm=2.5 -- chosen and SELF-CONSISTENTLY VERIFIED (see that script's docstring for the
# full derivation, including a falsified first hypothesis at max_norm~=0.10) to target
# skip_0's own natural raw-grad range (~2.2-2.98), producing a genuine clip/no-clip straddle:
# sample0 crosses between steps 8->9 (ratio 1.0095 -> 0.9995, a near-exact tie) and sample1
# crosses between steps 1->2 (ratio 1.0058 -> 0.9938) -- both within ~1% of the boundary.
# sample2 stays always-clip (ratio 1.07-1.19) throughout -- not itself a straddle, but doesn't
# need to be; "at least one node, some samples clip/some don't" is satisfied twice over by
# sample0/sample1.
#
# Like the sibling stable-track file, this does NOT use @test/@testset pass-fail gating -- it
# reports pass/fail counts at several tolerances and the worst required tolerance, PLUS a
# dedicated per-(step,node,sample) CLIP-DECISION agreement check at the specific near-boundary
# points identified above: does Julia agree with upstream on the DISCRETE clip/no-clip
# decision (not just the clipped value's numerical closeness)? A hairline float32 rounding
# disagreement right at the threshold would show up here as a "value diff" that's actually a
# BRANCH diff, not ordinary numerical noise -- and would be a materially different, more
# specific finding than the general relaxation-conditioning drift this whole session has been
# investigating.
using NPZ
using Test
using FabricPC
using Zygote
using Random

const FIXDIR = joinpath(@__DIR__, "fixtures")
const FIX_NCB = npzread(joinpath(FIXDIR, "tier_d_transformer_stable_normclip_boundary.npz"))
const FIX_SGD_NCB_XCHECK = npzread(joinpath(FIXDIR, "tier_d_transformer_stable_sgd.npz"))  # params0/batch cross-check only

const B, S, V, E, H = 3, 8, 10, 8, 2
const ETA_INFER = 0.01f0
const INFER_STEPS = 12
const MAX_NORM_NCB = 2.5f0
const NC_EPS = 1.0f-8

row_dt(v) = reshape(Float32.(v), 1, :)

const TIER_DT_FULL_NODES = ("embed", "transformer_0", "skip_0", "output")

# ---------------------------------------------------------------------------------------
# Sanity: params0/batch must be byte-identical to the sibling stable fixtures (single
# un-forked RNG split() stream shared by all tier_d_transformer_stable_* generators).
# ---------------------------------------------------------------------------------------
function check_shared_params0_batch()
    nmismatch = 0
    for k in keys(FIX_SGD_NCB_XCHECK)
        ks = String(k)
        if startswith(ks, "params0_") || startswith(ks, "batch_")
            a = FIX_SGD_NCB_XCHECK[ks]
            b = FIX_NCB[ks]
            if a != b
                println("  MISMATCH vs sibling SGD fixture at key=$ks")
                nmismatch += 1
            end
        end
    end
    println("params0/batch byte-identity vs tier_d_transformer_stable_sgd.npz: ",
        nmismatch == 0 ? "OK (all match)" : "$(nmismatch) MISMATCHES")
    return nmismatch
end

# ---------------------------------------------------------------------------------------
# Collect (label, julia_array, fixture_array) triples -- no @test, just data.
# ---------------------------------------------------------------------------------------
function collect_state_pairs!(pairs, prefix::AbstractString, state, FIX)
    for name in TIER_DT_FULL_NODES
        ns = state.nodes[name]
        push!(
            pairs,
            ("$(prefix)_$(name)_z_latent", ns.z_latent, FIX["$(prefix)_$(name)_z_latent"])
        )
        push!(pairs, ("$(prefix)_$(name)_z_mu", ns.z_mu, FIX["$(prefix)_$(name)_z_mu"]))
        push!(pairs, ("$(prefix)_$(name)_error", ns.error, FIX["$(prefix)_$(name)_error"]))
        push!(
            pairs, ("$(prefix)_$(name)_energy", ns.energy, FIX["$(prefix)_$(name)_energy"])
        )
        push!(
            pairs,
            (
                "$(prefix)_$(name)_latent_grad",
                ns.latent_grad,
                FIX["$(prefix)_$(name)_latent_grad"]
            )
        )
    end
    ni = state.nodes["input"]
    push!(
        pairs,
        ("$(prefix)_input_z_latent", ni.z_latent, FIX["$(prefix)_input_z_latent"] .+ 1.0f0)
    )
    expected_input_zmu = if prefix == "init"
        zeros(Float32, size(ni.z_mu))
    else
        (FIX["$(prefix)_input_z_latent"] .+ 1.0f0)
    end
    push!(pairs, ("$(prefix)_input_z_mu", ni.z_mu, expected_input_zmu))
    push!(pairs, ("$(prefix)_input_error", ni.error, FIX["$(prefix)_input_error"]))
    push!(pairs, ("$(prefix)_input_energy", ni.energy, FIX["$(prefix)_input_energy"]))
    push!(
        pairs,
        ("$(prefix)_input_latent_grad", ni.latent_grad, FIX["$(prefix)_input_latent_grad"])
    )
    return pairs
end

function collect_params_pairs!(pairs, prefix::AbstractString, gp, FIX)
    push!(
        pairs,
        (
            "$(prefix)_embed_w__embeddings",
            gp.nodes["embed"].weights["embeddings"],
            FIX["$(prefix)_embed_w__embeddings"]
        )
    )
    tb = gp.nodes["transformer_0"]
    for k in ("W_q", "W_k", "W_v", "W_o", "W_ff1", "W_ff2")
        push!(
            pairs,
            (
                "$(prefix)_transformer_0_w__$(k)",
                tb.weights[k],
                FIX["$(prefix)_transformer_0_w__$(k)"]
            )
        )
    end
    for k in ("ln1_gamma", "ln2_gamma")
        push!(
            pairs,
            (
                "$(prefix)_transformer_0_w__$(k)",
                vec(tb.weights[k]),
                vec(FIX["$(prefix)_transformer_0_w__$(k)"])
            )
        )
    end
    for k in ("b_q", "b_k", "b_v", "b_o", "b_ff1", "b_ff2", "ln1_beta", "ln2_beta")
        push!(
            pairs,
            (
                "$(prefix)_transformer_0_b__$(k)",
                vec(tb.biases[k]),
                vec(FIX["$(prefix)_transformer_0_b__$(k)"])
            )
        )
    end
    out = gp.nodes["output"]
    push!(
        pairs,
        (
            "$(prefix)_output_w__W_out",
            out.weights["W_out"],
            FIX["$(prefix)_output_w__W_out"]
        )
    )
    push!(
        pairs,
        (
            "$(prefix)_output_b__b_out",
            vec(out.biases["b_out"]),
            vec(FIX["$(prefix)_output_b__b_out"])
        )
    )
    return pairs
end

allclose_dt(a, b; rtol=1.0f-4, atol=1.0f-4) = all(abs.(a .- b) .<= atol .+ rtol .* abs.(b))

"""Minimum t (used as both rtol AND atol) such that `allclose_dt(a, b; rtol=t, atol=t)`
passes: max elementwise |a-b| / (1 + |b|)."""
function required_tol(a, b)
    d = abs.(Float64.(a) .- Float64.(b))
    denom = 1.0 .+ abs.(Float64.(b))
    isempty(d) ? 0.0 : maximum(d ./ denom)
end

function build_params(FIX)
    GraphParams(
        Dict(
            "input" => NodeParams(
                Dict{String, Matrix{Float32}}(), Dict{String, Matrix{Float32}}()
            ),
            "embed" => NodeParams(
                Dict("embeddings" => FIX["params0_embed_w__embeddings"]),
                Dict{String, Matrix{Float32}}()
            ),
            "transformer_0" => NodeParams(
                Dict(
                    "W_q" => FIX["params0_transformer_0_w__W_q"],
                    "W_k" => FIX["params0_transformer_0_w__W_k"],
                    "W_v" => FIX["params0_transformer_0_w__W_v"],
                    "W_o" => FIX["params0_transformer_0_w__W_o"],
                    "W_ff1" => FIX["params0_transformer_0_w__W_ff1"],
                    "W_ff2" => FIX["params0_transformer_0_w__W_ff2"],
                    "ln1_gamma" => row_dt(FIX["params0_transformer_0_w__ln1_gamma"]),
                    "ln2_gamma" => row_dt(FIX["params0_transformer_0_w__ln2_gamma"])
                ),
                Dict(
                    "b_q" => row_dt(FIX["params0_transformer_0_b__b_q"]),
                    "b_k" => row_dt(FIX["params0_transformer_0_b__b_k"]),
                    "b_v" => row_dt(FIX["params0_transformer_0_b__b_v"]),
                    "b_o" => row_dt(FIX["params0_transformer_0_b__b_o"]),
                    "b_ff1" => row_dt(FIX["params0_transformer_0_b__b_ff1"]),
                    "b_ff2" => row_dt(FIX["params0_transformer_0_b__b_ff2"]),
                    "ln1_beta" => row_dt(FIX["params0_transformer_0_b__ln1_beta"]),
                    "ln2_beta" => row_dt(FIX["params0_transformer_0_b__ln2_beta"])
                )
            ),
            "skip_0" => NodeParams(
                Dict{String, Matrix{Float32}}(), Dict{String, Matrix{Float32}}()
            ),
            "output" => NodeParams(
                Dict("W_out" => FIX["params0_output_w__W_out"]),
                Dict("b_out" => row_dt(FIX["params0_output_b__b_out"]))
            )
        )
    )
end

"""Run init -> relax01..12 -> converged -> grad -> train_step, collecting (label, julia,
fixture) pairs against FIX AND recording the per-step per-sample latent_grad L2 norm for
embed/transformer_0/skip_0 (the 3 non-clamped nodes actually subject to the norm-clip
decision -- `output` is clamped, so `compute_new_latent`/the clip is never invoked for it)."""
function run_pipeline(structure, FIX)
    pairs = Tuple{String, Any, Any}[]
    params = build_params(FIX)
    collect_params_pairs!(pairs, "params0", params, FIX)

    Xb = Float32.(FIX["batch_x"]) .+ 1.0f0
    Yb = FIX["batch_y"]
    clamps = Dict{String, Any}("input" => Xb, "output" => Yb)
    rng = Random.default_rng()

    init_state = initialize_graph_state(structure, B, rng; clamps=clamps, params=params)
    collect_state_pairs!(pairs, "init", init_state, FIX)

    norm_log = Dict(
        name => Vector{Vector{Float32}}() for name in ("embed", "transformer_0", "skip_0")
    )
    relax_state = init_state
    for step in 1:INFER_STEPS
        relax_state = FabricPC.inference_step(params, relax_state, clamps, structure)
        collect_state_pairs!(pairs, "relax$(lpad(step, 2, '0'))", relax_state, FIX)
        for name in ("embed", "transformer_0", "skip_0")
            g = relax_state.nodes[name].latent_grad
            # per-sample L2 norm over all non-batch dims (dims 2:end; Julia arrays are
            # (batch, ...) here matching the fixture's row-major batch-first convention)
            nrm = Float32[
                sqrt(sum(abs2, view(g, i, ntuple(_ -> Colon(), ndims(g) - 1)...))) for
                i in 1:size(g, 1)
            ]
            push!(norm_log[name], nrm)
        end
    end

    converged = run_inference(params, init_state, clamps, structure)
    collect_state_pairs!(pairs, "converged", converged, FIX)

    batch = Dict{String, Any}("x" => Xb, "y" => Yb)
    grads, energy, grad_final_state = get_graph_param_gradient(
        params, batch, structure, rng
    )
    collect_params_pairs!(pairs, "grad", grads, FIX)
    push!(
        pairs,
        ("scalars_energy_pretrain", [Float32(energy)], FIX["scalars_energy_pretrain"])
    )
    collect_state_pairs!(pairs, "grad_final", grad_final_state, FIX)

    LR = 0.05
    new_params, energy2, final_state2 = train_step(params, batch, structure, LR, rng)
    collect_params_pairs!(pairs, "trained", new_params, FIX)
    push!(
        pairs,
        ("scalars_energy_trainstep", [Float32(energy2)], FIX["scalars_energy_trainstep"])
    )
    collect_state_pairs!(pairs, "trained_final", final_state2, FIX)

    return pairs, norm_log
end

function report(label, pairs)
    println("\n" * "="^100)
    println(label, " -- ", length(pairs), " comparisons")
    println("="^100)
    for tol in (1.0f-4, 1.0f-5, 1.0f-6, 1.0f-7)
        npass = count(p -> allclose_dt(p[2], p[3]; rtol=tol, atol=tol), pairs)
        println("  tol=$(tol): $(npass)/$(length(pairs)) pass")
    end
    worst = 0.0
    worst_label = "none"
    for (name, a, b) in pairs
        t = required_tol(a, b)
        if t > worst
            worst = t
            worst_label = name
        end
    end
    println(
        "  WORST required tolerance across all $(length(pairs)) comparisons: $(worst)  (at $(worst_label))"
    )
    sorted = sort(pairs; by=p -> -required_tol(p[2], p[3]))
    println("  top 5 worst comparisons:")
    for (name, a, b) in sorted[1:min(5, end)]
        println("    $(name): required_tol=$(required_tol(a, b))")
    end
    return worst
end

"""Report Julia's clip/no-clip DISCRETE decision at every (step, sample) for skip_0 (the
node identified, by self-consistent measurement in the fixture generator, as genuinely
straddling max_norm=2.5), and flag any hairline-boundary sample (|ratio-1| < 20%)."""
function report_clip_boundary(norm_log)
    println("\n" * "="^100)
    println("CLIP-BOUNDARY AGREEMENT CHECK -- skip_0 node, max_norm=$(MAX_NORM_NCB)")
    println("="^100)
    nrms = norm_log["skip_0"]  # Vector of 12 (per-step) Float32[3] (per-sample)
    near_boundary = Tuple{Int, Int, Float32, Float32, Bool}[]  # (step, sample, norm, ratio, clips)
    for step in 1:INFER_STEPS
        for s in 1:B
            n = nrms[step][s]
            ratio = n / MAX_NORM_NCB
            clips = ratio > 1.0f0
            flag = abs(ratio - 1.0f0) <= 0.20f0 ? "  <-- NEAR BOUNDARY" : ""
            println(
                "  step=$(lpad(step,2)) sample=$(s) julia_raw_norm=$(round(n,digits=5)) " *
                "ratio=$(round(ratio,digits=4)) $(clips ? "CLIP" : "no-clip")$(flag)"
            )
            if abs(ratio - 1.0f0) <= 0.20f0
                push!(near_boundary, (step, s, n, ratio, clips))
            end
        end
    end
    return near_boundary
end

println("Building structures...")

# Hand-built graph for InferenceSGDNormClip at max_norm=2.5 (mirrors test_tier_d_transformer_
# stable.jl's own structure_nc construction exactly -- transformer_lm() hardcodes plain
# InferenceSGD, no keyword to swap algorithms -- just with max_norm=2.5 instead of 1.0).
input_nc = IdentityNode((S,), "input")
embed_nc = EmbeddingNode(
    (S, E), "embed"; vocab_size=V, weight_init=NormalInitializer(; std=1.0)
)
block_nc = TransformerBlock(
    (S, E), "transformer_0"; num_heads=H, ff_dim=nothing, use_rope=true, causal=true
)
skip_nc = SkipConnection((S, E), "skip_0")
output_nc = VocabProjectionNode(
    (S, V), "output"; weight_init=NormalInitializer(; std=sqrt(1.0 / E))
)
nodes_ncb = FabricPC.AbstractNode[input_nc, embed_nc, block_nc, skip_nc, output_nc]
edges_ncb = Edge[
    Edge(input_nc, slot(embed_nc, "in")),
    Edge(embed_nc, slot(block_nc, "in")),
    Edge(embed_nc, slot(skip_nc, "in")),
    Edge(block_nc, slot(skip_nc, "in")),
    Edge(skip_nc, slot(output_nc, "in"))
]
inference_ncb = InferenceSGDNormClip(;
    eta_infer=ETA_INFER, infer_steps=INFER_STEPS, latent_decay=0.0f0, max_norm=MAX_NORM_NCB,
    eps=NC_EPS
)
structure_ncb = graph(
    nodes_ncb, edges_ncb, TaskMap(; x=input_nc, y=output_nc), inference_ncb
)

println("\nChecking params0/batch byte-identity against sibling stable fixtures...")
check_shared_params0_batch()

println(
    "\nRunning InferenceSGDNormClip (eta=0.01, max_norm=2.5, eps=1e-8) pipeline vs tier_d_transformer_stable_normclip_boundary.npz ..."
)
pairs_ncb, norm_log = run_pipeline(structure_ncb, FIX_NCB)
worst_ncb = report(
    "InferenceSGDNormClip, eta_infer=0.01, max_norm=2.5, 12 steps", pairs_ncb
)

near_boundary = report_clip_boundary(norm_log)

println("\n" * "="^100)
println("SUMMARY")
println("="^100)
npass = count(p -> allclose_dt(p[2], p[3]), pairs_ncb)
println(
    "NormClip-boundary variant: $(npass)/$(length(pairs_ncb)) pass at 1e-4;  worst required tol = $(worst_ncb)"
)
println(
    "Near-boundary (|ratio-1|<=20%) skip_0 (step,sample) points found: $(length(near_boundary))"
)
for (step, s, n, ratio, clips) in near_boundary
    println(
        "  step=$(step) sample=$(s) julia_norm=$(n) ratio=$(ratio) julia_decision=$(clips ? "CLIP" : "no-clip")"
    )
end

# ---------------------------------------------------------------------------------------
# ACTUAL GATING (report() above is diagnostic). TOLERANCE: rtol=atol=1f-4 -- Float32 BLAS/XLA
# associativity across multiple chained inference steps, same convention every Tier D test in
# this repo uses. The discrete clip/no-clip assertion is the point of this file: it fails if
# Julia and upstream disagree on the BRANCH, not just the clipped value's numerical closeness.
@testset "Tier D conformance (upstream JAX FabricPC, transformer-LM, InferenceSGDNormClip boundary-straddle, max_norm=2.5, rtol/atol 1e-4)" begin
    @testset "value comparisons" begin
        for (name, a, b) in pairs_ncb
            @test allclose_dt(a, b)
        end
    end
    @testset "discrete clip/no-clip decision agreement at near-boundary points" begin
        @test !isempty(near_boundary)  # the whole point of this fixture: it must actually straddle
        for (step, s, n, ratio, clips) in near_boundary
            # same per-sample L2-norm-over-non-batch-dims formula run_pipeline used for Julia's
            # own norm_log, applied here to the FIXTURE's (upstream) latent_grad array instead --
            # an independent recomputation, not a re-read of Julia's own already-checked value.
            g_fix = FIX_NCB["relax$(lpad(step, 2, '0'))_skip_0_latent_grad"]
            fixture_norm = sqrt(
                sum(abs2, view(g_fix, s, ntuple(_ -> Colon(), ndims(g_fix) - 1)...))
            )
            fixture_clips = (fixture_norm / MAX_NORM_NCB) > 1.0f0
            @test clips == fixture_clips
        end
    end
end
