# STATUS (2026-07-13): 146/175 -- NOT green. Gated out of runtests.jl's default run
# (FABRICPC_TIER_D_TRANSFORMER=1 to include). Every pre-relaxation assertion (params0,
# initialize_graph_state) is bit-exact; all 29 failures are post-relaxation, after real
# 12-step attention loops, with per-element margins ~1.3-1.7x over the 1e-4 threshold that
# grow with iteration count and are never gross/NaN/wrong-signed -- root-caused to Float32
# BLAS-associativity drift (see the TOLERANCE note below), not a located logic bug (FD-
# validated gradients + line-by-line RoPE/mask/LayerNorm/GELU/residual checks all matched
# upstream exactly). See docs/AUDIT_REGISTER.md section 6 for the full writeup.
#
# Tier D conformance (docs/AUDIT_REGISTER.md section 6), TRANSFORMER-LM track: END-TO-END --
# initialize_graph_state -> run_inference (to convergence, 12 steps) -> get_graph_param_gradient
# (its own fresh 12-step run_inference) -> exactly ONE train_step, on a real *assembled graph*
# matching src/models/transformer_lm.jl's `transformer_lm(seq_len=8, vocab_size=10, embed_dim=8,
# num_heads=2, num_blocks=1)` topology -- vs the pinned upstream JAX FabricPC checkout. Unlike
# Tier C (a tiny 3-node feedforward graph), this proves the WHOLE multi-head-attention /
# RoPE / LayerNorm / residual / embedding-lookup / vocab-projection stack computes what
# upstream computes, chained across a real relaxation trajectory. Fixtures generated by
# scripts/generate_tier_d_transformer_fixtures.py into fixtures/tier_d_transformer.npz -- see
# that script's docstring (six numbered DIVERGENCE-HANDLING sections) for the full rationale;
# the three that matter for THIS file are summarized inline below at their point of use.
#
# Requires the Phase-D Zygote autodiff seam: TransformerBlock and VocabProjectionNode
# implement only `compute_mu` (autodiff.jl's generic forward_and_weight_grads/
# forward_and_latent_grads differentiate it) -- Enzyme aborts on the multi-head-attention
# block on Julia 1.12 ("addToDiffe: unhandled accumulate with partial sizes"), so this suite
# is Zygote-only (`using Zygote` below; runtests.jl already loads it top-level before the
# testset for exactly this reason -- see its own comment).
using Test
using NPZ
using FabricPC
using Zygote
using Random

const FIX_DT = npzread(joinpath(@__DIR__, "fixtures", "tier_d_transformer.npz"))

# numpy.allclose semantics (per-element: |a-b| <= atol + rtol*|b|), NOT Julia's built-in array
# `≈` (a single norm-based check) -- separate name from every earlier tier's own helper
# (FIX/FIX_B/FIX_C/FIX_D + allclose/allclose_b/allclose_c/allclose_d are already `include`d
# earlier in runtests.jl and share this file's Main scope) so no tier's constants shadow
# another's.
#
# TOLERANCE: rtol=atol=1e-4, looser than Tier C's 1e-5. Reason:
#   "Float32 BLAS associativity across multiple inference steps"
# This fixture chains THREE separate 12-step relaxation trajectories (initialize_graph_state's
# own init -> run_inference; get_graph_param_gradient's internal re-init -> re-run_inference;
# train_step's internal call to the same), each step doing real multi-head-attention matmuls
# (Q/K/V projections, softmax, RoPE rotations, two LayerNorms, a GELU MLP) whose reduction
# order can differ between XLA (upstream) and OpenBLAS (Julia) at every single step -- so
# small per-step Float32 rounding differences compound across each 12-step trajectory rather
# than being checked once in isolation, and can legitimately push element-wise deltas past
# Tier C's tighter single-loop 1e-5 bound without indicating a real bug.
allclose_dt(a, b; rtol=1.0f-4, atol=1.0f-4) = all(abs.(a .- b) .<= atol .+ rtol .* abs.(b))

# Flattens an upstream bias/gamma/beta array of ANY shape (upstream dumps TransformerBlock's
# as (1,1,E)/(1,1,ff) and VocabProjectionNode's b_out as a bare (vocab,) 1-D array -- see the
# generator's DIVERGENCE-HANDLING notes) into the genuine 2-D (1,n) `Matrix{Float32}` our
# Julia nodes require: TransformerBlock's compute_mu reshapes b_ff1 via
# `size(params.biases["b_ff1"], 2)` (transformer.jl) and VocabProjectionNode's compute_mu
# reshapes b_out the same way (transformer_decomposed.jl) -- a raw 3-D/1-D array makes that
# `size(...,2)` read the WRONG dimension (1, not the real width) and either errors outright
# (DimensionMismatch) or silently mis-sizes; separately, `sgd_update` (train.jl) rebuilds
# weights/biases into a `Dict{String,Matrix{Float32}}`, which a 3-D array cannot convert to.
# Mirrors test_tier_b.jl's own `row(v) = reshape(Float32.(v), 1, :)` helper (there scoped
# inside one @testset; this one is used across the whole file, hence the `_dt` suffix to
# avoid colliding with any other tier's same-named local).
row_dt(v) = reshape(Float32.(v), 1, :)

# Full byte-for-byte comparable nodes: everything except "input" (see below) and "mask"
# (TOPOLOGY DIVERGENCE #1 in the generator's docstring -- upstream's TransformerBlock has a
# real second "mask" slot fed by an explicit IdentityNode; Julia's TransformerBlock has NO
# such slot at all, masking future keys inline via its `causal::Bool` flag instead, verified
# mathematically equivalent in the generator's own docstring. There is no Julia node named
# "mask" and this file never reads a single "*_mask_*" fixture key.)
const TIER_DT_FULL_NODES = ("embed", "transformer_0", "skip_0", "output")

"""
    check_tier_dt_state(prefix, state)

Assert every dumped `GraphState` field (z_latent/z_mu/error/energy/
latent_grad) for fixture prefix `prefix` (e.g. "init"/"converged"/"grad_final"/
"trained_final") against the live Julia `state`, for every node with no cross-language
divergence ([`TIER_DT_FULL_NODES`](@ref)), plus a divergence-aware partial check of "input".
"""
function check_tier_dt_state(prefix::AbstractString, state::GraphState)
    for name in TIER_DT_FULL_NODES
        ns = state.nodes[name]
        @test allclose_dt(ns.z_latent, FIX_DT["$(prefix)_$(name)_z_latent"])
        @test allclose_dt(ns.z_mu, FIX_DT["$(prefix)_$(name)_z_mu"])
        @test allclose_dt(ns.error, FIX_DT["$(prefix)_$(name)_error"])
        @test allclose_dt(ns.energy, FIX_DT["$(prefix)_$(name)_energy"])
        # SHAPE, not just values — energy is per-sample `(batch,)` on both stacks; upstream
        # b6f64ad moved only WHERE the batch->scalar sum happens, never the field's shape.
        # An allclose alone would let a scalar broadcast against the fixture; this fails first.
        @test size(ns.energy) == size(FIX_DT["$(prefix)_$(name)_energy"]) == (state.batch_size,)
        # A long-standing carve-out lived here: "output" (VocabProjectionNode) was excluded from
        # the pre_activation assertion because upstream's override never assigned that field,
        # while our generic seam always set pre_activation = z_mu — so the fixture key held the
        # all-zero state-init default and the two sides were comparing different quantities.
        # Upstream b6f64ad deleted pre_activation from NodeState outright, which dissolves the
        # divergence rather than papering over it: there is no field, no carve-out, and every
        # node is asserted uniformly above.
        @test allclose_dt(ns.latent_grad, FIX_DT["$(prefix)_$(name)_latent_grad"])
    end

    # "input" (IdentityNode, in_degree=0, always clamped on every call below): TOKEN ID
    # CONVENTION divergence (generator docstring, divergence #6). Upstream's token ids are
    # 0-based (fed straight into a 0-based JAX embedding-table index); ours are 1-based
    # (EmbeddingNode's `_embed_lookup` does `Int(round(idx[b,s]))` into a 1-based Julia
    # array), so we clamp "input" with `batch_x .+ 1` below -- z_latent therefore carries a
    # constant +1 offset from the fixture at EVERY phase (an always-clamped source latent
    # that `update_latents` never touches: it stays exactly `batch_x + 1` throughout). z_mu
    # inherits the same offset only from the phase where the terminal `z_mu <- z_latent`
    # copy has actually fired at least once (verified against base.py's
    # `forward_and_latent_grads`, in_degree==0 branch, and the identically-structured Julia
    # branch in identity.jl): that copy lives INSIDE `forward_and_latent_grads`, which
    # `initialize_graph_state`'s FeedforwardStateInit explicitly skips for in_degree==0 nodes
    # (state_initializer.jl: `info.in_degree > 0 || continue`) -- so z_mu is still the
    # all-zero array the very first pass allocated at "init", and only picks up the
    # +1-shifted z_latent value from "converged" onward (confirmed bit-exact against the
    # fixture itself: `init_input_z_mu` is all zero, `converged_input_z_mu ==
    # converged_input_z_latent` exactly).
    ni = state.nodes["input"]
    @test allclose_dt(ni.z_latent, FIX_DT["$(prefix)_input_z_latent"] .+ 1.0f0)
    expected_input_zmu = prefix == "init" ? zeros(Float32, size(ni.z_mu)) :
        (FIX_DT["$(prefix)_input_z_latent"] .+ 1.0f0)
    @test allclose_dt(ni.z_mu, expected_input_zmu)
    # error/energy/latent_grad carry NO token-id encoding at all -- the
    # terminal special case forces every one of them to exactly zero on both sides at every
    # phase (verified against the fixture directly) -- so these ARE plain cross-language
    # comparisons, and would catch a real bug in the terminal-source branch.
    @test allclose_dt(ni.error, FIX_DT["$(prefix)_input_error"])
    @test allclose_dt(ni.energy, FIX_DT["$(prefix)_input_energy"])
    @test allclose_dt(ni.latent_grad, FIX_DT["$(prefix)_input_latent_grad"])
end

"""
    check_tier_dt_params(prefix, gp)

Assert the dumped `embed`/`transformer_0`/`output` weights + biases for fixture prefix
`prefix` (e.g. "params0"/"grad"/"trained" -- the same key shape is used for gradients as for
values) against the live Julia `GraphParams` `gp`. "input" and "skip_0" carry no learnable
params (source node / plain summation) so there is nothing to compare for them.
"""
function check_tier_dt_params(prefix::AbstractString, gp::GraphParams)
    @test allclose_dt(
        gp.nodes["embed"].weights["embeddings"], FIX_DT["$(prefix)_embed_w__embeddings"]
    )

    tb = gp.nodes["transformer_0"]
    for k in ("W_q", "W_k", "W_v", "W_o", "W_ff1", "W_ff2")
        @test allclose_dt(tb.weights[k], FIX_DT["$(prefix)_transformer_0_w__$(k)"])
    end
    # gamma/beta/biases: vec(...) both sides -- upstream dumps these (1,1,E)/(1,1,ff), ours
    # are real (1,n) 2-D (see row_dt above); flattening sidesteps the shape mismatch (same n
    # values either way, no reordering across singleton leading dims), matching
    # test_tier_b.jl's own established convention for this exact node family.
    for k in ("ln1_gamma", "ln2_gamma")
        @test allclose_dt(vec(tb.weights[k]), vec(FIX_DT["$(prefix)_transformer_0_w__$(k)"]))
    end
    for k in ("b_q", "b_k", "b_v", "b_o", "b_ff1", "b_ff2", "ln1_beta", "ln2_beta")
        @test allclose_dt(vec(tb.biases[k]), vec(FIX_DT["$(prefix)_transformer_0_b__$(k)"]))
    end

    out = gp.nodes["output"]
    @test allclose_dt(out.weights["W_out"], FIX_DT["$(prefix)_output_w__W_out"])
    @test allclose_dt(vec(out.biases["b_out"]), vec(FIX_DT["$(prefix)_output_b__b_out"]))
end

@testset "Tier D conformance (upstream JAX FabricPC, end-to-end, transformer-LM, rtol/atol 1e-4)" begin
    B, S, V, E, H = 3, 8, 10, 8, 2

    # transformer_lm's own defaults already match the fixture's TINY CONFIG exactly (no
    # override needed): ff_dim=nothing -> 4*embed_dim=32, infer_steps=nothing ->
    # 3*(2*num_blocks+2)=12, eta_infer=0.1, use_rope=true, causal=true (hardcoded inside
    # transformer_lm for every block), scaling=nothing (muPC off) -- see
    # generate_tier_d_transformer_fixtures.py's TINY CONFIG comment and its DIVERGENCE #3/#5
    # for the independent verification that these already coincide with upstream's own
    # per-call config on this fixture, not just the class defaults.
    structure = transformer_lm(;
        seq_len=S, vocab_size=V, embed_dim=E, num_heads=H, num_blocks=1
    )

    # RNG TRAP (same discipline as every earlier tier): GraphParams built DIRECTLY from the
    # fixture's jax.random-generated arrays, never Julia's own `initialize_params` (a
    # different RNG algorithm than jax.random). "input"/"skip_0" carry no params at all
    # (IdentityNode / plain-sum SkipConnection). Bias/gamma/beta entries go through
    # `row_dt` (see its docstring above); weight matrices (W_q/.../W_out/embeddings) are
    # already the same 2-D shape on both sides and need no reshape.
    params = GraphParams(
        Dict(
            "input" => NodeParams(
                Dict{String, Matrix{Float32}}(), Dict{String, Matrix{Float32}}()
            ),
            "embed" => NodeParams(
                Dict("embeddings" => FIX_DT["params0_embed_w__embeddings"]),
                Dict{String, Matrix{Float32}}()
            ),
            "transformer_0" => NodeParams(
                Dict(
                    "W_q" => FIX_DT["params0_transformer_0_w__W_q"],
                    "W_k" => FIX_DT["params0_transformer_0_w__W_k"],
                    "W_v" => FIX_DT["params0_transformer_0_w__W_v"],
                    "W_o" => FIX_DT["params0_transformer_0_w__W_o"],
                    "W_ff1" => FIX_DT["params0_transformer_0_w__W_ff1"],
                    "W_ff2" => FIX_DT["params0_transformer_0_w__W_ff2"],
                    "ln1_gamma" => row_dt(FIX_DT["params0_transformer_0_w__ln1_gamma"]),
                    "ln2_gamma" => row_dt(FIX_DT["params0_transformer_0_w__ln2_gamma"])
                ),
                Dict(
                    "b_q" => row_dt(FIX_DT["params0_transformer_0_b__b_q"]),
                    "b_k" => row_dt(FIX_DT["params0_transformer_0_b__b_k"]),
                    "b_v" => row_dt(FIX_DT["params0_transformer_0_b__b_v"]),
                    "b_o" => row_dt(FIX_DT["params0_transformer_0_b__b_o"]),
                    "b_ff1" => row_dt(FIX_DT["params0_transformer_0_b__b_ff1"]),
                    "b_ff2" => row_dt(FIX_DT["params0_transformer_0_b__b_ff2"]),
                    "ln1_beta" => row_dt(FIX_DT["params0_transformer_0_b__ln1_beta"]),
                    "ln2_beta" => row_dt(FIX_DT["params0_transformer_0_b__ln2_beta"])
                )
            ),
            "skip_0" => NodeParams(
                Dict{String, Matrix{Float32}}(), Dict{String, Matrix{Float32}}()
            ),
            "output" => NodeParams(
                Dict("W_out" => FIX_DT["params0_output_w__W_out"]),
                Dict("b_out" => row_dt(FIX_DT["params0_output_b__b_out"]))
            )
        )
    )

    @testset "params0 (construction sanity vs upstream jax.random init)" begin
        check_tier_dt_params("params0", params)
    end

    # TOKEN ID CONVENTION (divergence #6, see check_tier_dt_state's docstring above):
    # upstream's 0-based token ids -> Julia's 1-based EmbeddingNode lookup. `batch_y`
    # (one-hot next-token targets) needs NO such adjustment -- a one-hot column position is
    # read identically by both languages (it is data, never used as an array INDEX).
    Xb = Float32.(FIX_DT["batch_x"]) .+ 1.0f0          # (B, S), 1-based
    Yb = FIX_DT["batch_y"]                             # (B, S, V) one-hot, unadjusted

    # NODE-name-keyed (matches Tier C/D-MNIST's own `initialize_graph_state`/`run_inference`
    # clamps dict convention) -- no "mask" entry: Julia's graph has no such node (INLINE
    # CAUSAL MASK divergence, see TIER_DT_FULL_NODES comment above; transformer_lm.jl's own
    # top-of-file comment documents this as its divergence #1).
    clamps = Dict{String, Any}("input" => Xb, "output" => Yb)

    # STATE-INIT RNG NON-ISSUE (same argument as every earlier tier, re-verified for this
    # graph): "input" is the SOLE in_degree=0 node in Julia's graph (unlike upstream's two,
    # "input" + "mask" -- Julia simply has no "mask" node to be the second one) and is always
    # clamped below, so the rng argument threaded into every call here never affects a single
    # compared output array; any concrete `AbstractRNG` is fine.
    rng = Random.default_rng()

    init_state = initialize_graph_state(structure, B, rng; clamps=clamps, params=params)

    @testset "initialize_graph_state (vs upstream initialize_graph_state)" begin
        check_tier_dt_state("init", init_state)
    end

    converged = run_inference(params, init_state, clamps, structure)

    @testset "run_inference to convergence (vs upstream run_inference, 12 steps)" begin
        check_tier_dt_state("converged", converged)
    end

    # TASK-name-keyed (matches Tier C/D-MNIST's own `get_graph_param_gradient`/`train_step`
    # `batch` dict convention -- those generic functions build their OWN clamps internally by
    # walking `structure.task_map`, which is `Dict("x"=>"input", "y"=>"output")` here; no
    # "causal_mask" task exists on the Julia side to thread through, unlike upstream's CLAMP
    # PLUMBING note in the generator's docstring).
    batch = Dict{String, Any}("x" => Xb, "y" => Yb)
    grads, energy, grad_final_state = get_graph_param_gradient(params, batch, structure, rng)

    @testset "get_graph_param_gradient (vs upstream, own re-init from batch)" begin
        check_tier_dt_params("grad", grads)
        @test allclose_dt([Float32(energy)], FIX_DT["scalars_energy_pretrain"])
        check_tier_dt_state("grad_final", grad_final_state)
    end

    @testset "one train_step (vs upstream optax.sgd, lr=0.05)" begin
        LR = 0.05
        new_params, energy2, final_state2 = train_step(params, batch, structure, LR, rng)
        check_tier_dt_params("trained", new_params)
        @test allclose_dt([Float32(energy2)], FIX_DT["scalars_energy_trainstep"])
        check_tier_dt_state("trained_final", final_state2)
    end
end
