#!/usr/bin/env python3
"""
Tier D transformer-LM track -- E5 CONTRACTIVE-REGIME VARIANT (2026-07-14), decisive experiment
for docs/AUDIT_REGISTER.md section 6's open transformer-LM track (146/175 at eta_infer=0.1,
INFER_STEPS=12, rtol=atol=1e-4 -- see that file for the full 146/175 investigation and three
prior rounds of error-growth analysis).

DO NOT confuse this with scripts/generate_tier_d_transformer_fixtures.py / its
tier_d_transformer.npz baseline -- that file and its fixture are the documented
"eta=0.1/12-step, expansive, open" artifact and are UNTOUCHED by this script. This is a
SEPARATE, parallel fixture variant testing a specific diagnosis: the 12-step InferenceSGD
relaxation loop is literally gradient descent on energy w.r.t. latents, iteration matrix
(I - eta*H); it is contractive (perturbations shrink each step) iff eta < 2/lambda_max and
expansive (perturbations grow, compounding float32 noise into large cross-language
disagreements) iff eta > 2/lambda_max. Growth-rate evidence assembled across this session's
prior rounds implies the eta=0.1/12-step config is EXPANSIVE -- i.e. two independent float32
ports of an expansive iterative map cannot be expected to agree bit-for-bit after 12
iterations; that is a property of the map's conditioning, not of port fidelity (which Tier B,
151/151, and this track's OWN pre-relaxation checks, params0 19/19 + initialize_graph_state
29/29, already establish independently).

THIS SCRIPT: identical graph topology, node configs, and params/batch-generation recipe as
generate_tier_d_transformer_fixtures.py (same random seeds/RNG-split order, same architecture,
same INFER_STEPS=12 -- testing the SAME number of iterations, not a longer relaxation reaching
a different fixed point) -- the ONLY thing that changes is eta_infer: 0.1 -> 0.01. Predicted
eta*lambda ~= 0.1*36*(0.01/0.1) ~= 0.36, solidly inside the contractive region
(|1-eta*lambda| ~= 0.64 < 1); DIRECTLY measured (not just assumed) by the companion script
e5_amplification_eta01.py before this fixture is trusted -- see that script's own output for
the measured per-step amplification factor.

BONUS (C-05 conformance-harness coverage, docs/AUDIT_REGISTER.md section 4 -- C-05
InferenceSGDNormClip is ported+VERIFIED CLOSED but has ZERO conformance-harness coverage
despite that): this script ALSO generates a second fixture using InferenceSGDNormClip instead
of plain InferenceSGD, at the SAME eta_infer=0.01/infer_steps=12, max_norm=1.0/eps=1e-8 (C-05's
own test defaults, test/test_inference_normclip.jl's first testset), latent_decay=0.0 (both
classes' shared default). Both fixtures share the EXACT SAME params0/batch (generated by a
single, un-forked RNG split() stream) -- only the graph's `inference` object (and therefore
`structure`) differs between them; graph_construction.py's own `graph()` docstring guarantees
"copy-on-finalize: original node objects are not modified" (graph_construction.py:120), so the
SAME node objects are safely reused for both graph() calls below -- no risk of one call's
finalization leaking into the other.

All six DIVERGENCE-HANDLING decisions in generate_tier_d_transformer_fixtures.py's own
docstring (mask node / VocabProjectionNode activation+energy defaults / no muPC scaling /
VocabProjectionNode-not-Linear / rope_theta+internal_activation / 0-based-vs-1-based token ids)
apply IDENTICALLY here -- read that file for the full rationale; only the essential
per-decision facts are restated inline below at their point of use, not the full rationale.

Run with the upstream fabricpc package importable (same venv as every other Tier fixture):
    cd <this repo> && source /home/shivaji1012/dev-zone/FabricPC/.venv-fixtures/bin/activate
    python3 scripts/generate_tier_d_transformer_stable_fixtures.py
"""

import numpy as np
import jax
import jax.numpy as jnp
import optax

from fabricpc.core.activations import GeluActivation
from fabricpc.core.initializers import NormalInitializer
from fabricpc.core.inference import InferenceSGD, InferenceSGDNormClip, run_inference
from fabricpc.core.types import GraphParams, NodeParams
from fabricpc.core.topology import Edge
from fabricpc.graph_assembly.graph_construction import TaskMap, graph
from fabricpc.graph_initialization.state_initializer import initialize_graph_state
from fabricpc.nodes.identity import IdentityNode
from fabricpc.nodes.skip_connection import SkipConnection
from fabricpc.nodes.transformer import TransformerBlock
from fabricpc.nodes.transformer_v2 import EmbeddingNode, VocabProjectionNode
from fabricpc.training.train import get_graph_param_gradient, train_step
from fabricpc.training.train_autoregressive import create_causal_mask  # VALUE helper only

key = jax.random.PRNGKey(2026)  # SAME seed as generate_tier_d_transformer_fixtures.py


def split():
    global key
    key, sub = jax.random.split(key)
    return sub


def put(OUT, prefix, **arrays):
    for name, arr in arrays.items():
        OUT[f"{prefix}_{name}"] = np.asarray(arr)


def dump_state(OUT, prefix, state):
    for name, ns in state.nodes.items():
        put(
            OUT, f"{prefix}_{name}",
            z_latent=ns.z_latent, z_mu=ns.z_mu, error=ns.error, energy=ns.energy,
            latent_grad=ns.latent_grad,
        )


def dump_params(OUT, prefix, params):
    for name, np_ in params.nodes.items():
        for wname, w in np_.weights.items():
            put(OUT, f"{prefix}_{name}", **{f"w__{wname}": w})
        for bname, b in np_.biases.items():
            put(OUT, f"{prefix}_{name}", **{f"b__{bname}": b})


# =========================================================================================
# TINY CONFIG -- IDENTICAL to generate_tier_d_transformer_fixtures.py except ETA_INFER.
# =========================================================================================
B, S, V, E, H = 3, 8, 10, 8, 2
INFER_STEPS = 3 * (2 * 1 + 2)  # = 12 -- UNCHANGED (testing the SAME iteration count)
ETA_INFER = 0.01  # <-- THE ONLY CHANGE FROM THE BASELINE SCRIPT (was 0.1)
MAX_NORM = 1.0    # InferenceSGDNormClip -- matches C-05's own test default
NC_EPS = 1.0e-8    # InferenceSGDNormClip -- matches C-05's own test default

input_node = IdentityNode(shape=(S,), name="input")
mask_node = IdentityNode(shape=(1, S, S), name="mask")  # DIVERGENCE #1, see baseline script
embed_node = EmbeddingNode(
    shape=(S, E), name="embed", vocab_size=V, embed_dim=E,
    weight_init=NormalInitializer(std=1.0),
)
block = TransformerBlock(
    shape=(S, E), name="transformer_0", num_heads=H, ff_dim=None,
    use_rope=True, internal_activation=GeluActivation(), rope_theta=10000.0,
)
skip_node = SkipConnection(shape=(S, E), name="skip_0")
output_node = VocabProjectionNode(
    shape=(S, V), name="output", vocab_size=V, embed_dim=E,
    weight_init=NormalInitializer(std=float(np.sqrt(1.0 / E))),
    # activation/energy left at class default (Softmax + CrossEntropy) -- DIVERGENCE #2 in the
    # baseline script's docstring: this MATCHES Julia's current (post-565f9fb) default, do not
    # override to Identity+Gaussian.
)

nodes = [input_node, mask_node, embed_node, block, skip_node, output_node]
edges = [
    Edge(source=input_node, target=embed_node.slot("in")),
    Edge(source=embed_node, target=block.slot("in")),
    Edge(source=mask_node, target=block.slot("mask")),
    Edge(source=embed_node, target=skip_node.slot("in")),
    Edge(source=block, target=skip_node.slot("in")),
    Edge(source=skip_node, target=output_node.slot("in")),
]

# =========================================================================================
# params0 / batch -- generated ONCE, shared by BOTH fixture variants below (single un-forked
# split() stream, IDENTICAL RNG order to generate_tier_d_transformer_fixtures.py's own
# params0/batch section -- byte-reproducible against that script's own params0_*/batch_*
# arrays, since neither depends on eta_infer or the inference algorithm at all).
# =========================================================================================
embed_params = EmbeddingNode.initialize_params(
    split(), (S, E), {}, weight_init=NormalInitializer(std=1.0), config={"vocab_size": V, "embed_dim": E}
)
node_config_tb = {"num_heads": H, "ff_dim": None}
tb_params = TransformerBlock.initialize_params(
    split(), (S, E), {}, weight_init=None, config=node_config_tb
)
output_params = VocabProjectionNode.initialize_params(
    split(), (S, V), {}, weight_init=NormalInitializer(std=float(np.sqrt(1.0 / E))),
    config={"vocab_size": V, "embed_dim": E},
)

params = GraphParams(
    nodes={
        "input": NodeParams(weights={}, biases={}),
        "mask": NodeParams(weights={}, biases={}),
        "embed": embed_params,
        "transformer_0": tb_params,
        "skip_0": NodeParams(weights={}, biases={}),
        "output": output_params,
    }
)

Xb = jax.random.randint(split(), (B, S), 0, V)  # upstream-native 0-based ids, int32
labels = jax.random.randint(split(), (B, S), 0, V)
Yb = jax.nn.one_hot(labels, V)  # (B, S, V) one-hot next-token targets
mask_val = create_causal_mask(S)[None, None, :, :]
mask_val = jnp.broadcast_to(mask_val, (B, 1, S, S))

clamps = {"input": Xb, "output": Yb, "mask": mask_val}  # NODE-name-keyed
batch = {"x": Xb, "y": Yb, "causal_mask": mask_val}     # TASK-name-keyed

dummy_key = jax.random.PRNGKey(999)   # state-init RNG non-issue (see baseline script)
rng_key2 = jax.random.PRNGKey(777)    # get_graph_param_gradient/train_step RNG
LR = 0.05


def run_variant(algo_name, inference_obj, out_path):
    """Run the full init -> relax01..12 -> converged -> grad -> train_step pipeline for one
    inference algorithm, dumping to its own .npz. `nodes`/`edges` (module-level, shared) are
    safe to reuse across multiple graph() calls -- graph() copy-on-finalizes, never mutates
    the passed node objects (graph_construction.py:120's own docstring guarantee)."""
    OUT = {}
    structure = graph(
        nodes=nodes, edges=edges,
        task_map=TaskMap(x=input_node, y=output_node, causal_mask=mask_node),
        inference=inference_obj,
        # graph_state_initializer/scaling left unset -- DIVERGENCE #3, matches baseline script
    )
    dump_params(OUT, "params0", params)
    put(OUT, "batch", x=Xb, y=Yb, causal_mask=mask_val)

    init_state = initialize_graph_state(structure, B, dummy_key, clamps=clamps, params=params)
    dump_state(OUT, "init", init_state)

    inference_cls = type(inference_obj)
    relax_state = init_state
    for step in range(1, INFER_STEPS + 1):
        relax_state = inference_cls.inference_step(
            params, relax_state, clamps, structure, inference_obj.config
        )
        dump_state(OUT, f"relax{step:02d}", relax_state)

    converged = run_inference(params, init_state, clamps, structure)
    dump_state(OUT, "converged", converged)

    _max_sanity_diff = 0.0
    for _name, _ns in converged.nodes.items():
        _rns = relax_state.nodes[_name]
        for _field in ("z_latent", "z_mu", "error", "energy", "latent_grad"):
            _a = np.asarray(getattr(_ns, _field))
            _b = np.asarray(getattr(_rns, _field))
            _d = float(np.max(np.abs(_a - _b))) if _a.size else 0.0
            _max_sanity_diff = max(_max_sanity_diff, _d)
            assert np.allclose(_a, _b, rtol=1e-3, atol=1e-3), (
                f"[{algo_name}] INSTRUMENTATION SANITY FAILED: relax12 vs converged at "
                f"node={_name} field={_field} max|diff|={_d}"
            )
    print(f"[{algo_name}] SANITY OK: relax12 ~= converged (max|diff|={_max_sanity_diff:.3e})")

    grads, energy, grad_final_state = get_graph_param_gradient(params, batch, structure, rng_key2)
    dump_params(OUT, "grad", grads)
    put(OUT, "scalars", energy_pretrain=jnp.reshape(jnp.asarray(energy), (1,)))
    dump_state(OUT, "grad_final", grad_final_state)

    optimizer = optax.sgd(learning_rate=LR)
    opt_state = optimizer.init(params)
    new_params, new_opt_state, energy2, final_state2 = train_step(
        params, opt_state, batch, structure, optimizer, rng_key2
    )
    dump_params(OUT, "trained", new_params)
    put(OUT, "scalars", energy_trainstep=jnp.reshape(jnp.asarray(energy2), (1,)))
    dump_state(OUT, "trained_final", final_state2)

    np.savez(out_path, **OUT)
    print(f"[{algo_name}] wrote {len(OUT)} arrays to {out_path}")


run_variant(
    "stable_sgd",
    InferenceSGD(eta_infer=ETA_INFER, infer_steps=INFER_STEPS),
    "test/conformance/fixtures/tier_d_transformer_stable_sgd.npz",
)
run_variant(
    "stable_normclip",
    InferenceSGDNormClip(
        eta_infer=ETA_INFER, infer_steps=INFER_STEPS, latent_decay=0.0,
        max_norm=MAX_NORM, eps=NC_EPS,
    ),
    "test/conformance/fixtures/tier_d_transformer_stable_normclip.npz",
)
